// Curriculum data — modules grouped, each with multiple steps.
// Step types: 'theory' (text only) or 'exercise' (sheet + audio).

export const MODULES = [
  // ================= SCALES =================
  {
    id: 'major-scale',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'The Major Scale',
    summary: 'Build, hear and recognise the major scale family.',
    steps: [
      {
        type: 'theory',
        title: 'Pattern of whole and half steps',
        text: `The major scale is built from a fixed pattern of intervals: <strong>W-W-H-W-W-W-H</strong> (W = whole step / 2 semitones, H = half step / 1 semitone). Starting from C, every white key in order gives you C major: C D E F G A B C. The half steps fall between E–F and B–C. This pattern is what makes the scale sound bright and "resolved".`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '3', '4', '5', '6', '7', '8'],
          steps: ['W', 'W', 'H', 'W', 'W', 'W', 'H'],
        },
        audio: [60, 62, 64, 65, 67, 69, 71, 72],
        references: [
          'Twinkle Twinkle Little Star — pure C major',
          'Let It Be (The Beatles) — built on a major key',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Hear the C major scale ascending, one note per beat.',
        notes: [60, 62, 64, 65, 67, 69, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'The same scale played in reverse — feel how it resolves coming back to the tonic.',
        notes: [72, 71, 69, 67, 65, 64, 62, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With rhythm',
        description: 'Major scale fragment with a quarter–eighth–eighth feel. Notice how rhythm reshapes a familiar scale.',
        notes: [60, 64, 67, 64, 65, 69, 67, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Singable melody',
        description: 'A short, catchy melody using only major scale notes — the kind of phrase that sticks in your head.',
        notes: [60, 62, 64, 67, 64, 65, 64, 60],
        style: 'melody',
      },
    ],
  },
  {
    id: 'natural-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Natural Minor Scale',
    summary: 'The minor counterpart of major. Same notes as A minor played from A.',
    steps: [
      {
        type: 'theory',
        title: 'A minor and the relative key',
        text: `Natural minor uses the same notes as the major scale starting on the 6th degree. C major shares notes with A natural minor: A B C D E F G A. Its interval pattern is <strong>W-H-W-W-H-W-W</strong> — the half steps now fall between B–C and E–F. The lowered 3rd, 6th and 7th compared to major give it that darker, contemplative colour.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '♭3', '4', '5', '♭6', '♭7', '8'],
          steps: ['W', 'H', 'W', 'W', 'H', 'W', 'W'],
        },
        audio: [69, 71, 72, 74, 76, 77, 79, 81],
        references: [
          'Stairway to Heaven (Led Zeppelin) — A minor',
          'Hotel California (Eagles) — uses natural minor freely',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending in A',
        description: 'Climb A natural minor.',
        notes: [69, 71, 72, 74, 76, 77, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending in A',
        description: 'Same scale coming back down. Listen to the lowered 7th (G) instead of G♯.',
        notes: [81, 79, 77, 76, 74, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Sad melody',
        description: 'Short melodic phrase that uses the lowered 6th and 7th — that natural-minor wistful feel.',
        notes: [69, 72, 71, 69, 67, 65, 67, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Climbing line',
        description: 'Stepwise melodic line with neighbour tones.',
        notes: [69, 71, 72, 71, 74, 76, 74, 72],
        style: 'melody',
      },
    ],
  },
  {
    id: 'pentatonic-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Pentatonic Minor',
    summary: 'Five-note scale. The backbone of blues, rock and pop solos.',
    steps: [
      {
        type: 'theory',
        title: 'Why five notes?',
        text: `Pentatonic minor is natural minor with the 2nd and 6th degrees removed: <strong>1 ♭3 4 5 ♭7</strong>. Removing those half steps eliminates the most "dissonant" intervals — every note sounds good against the others, which is why solos built on the pentatonic rarely clash. In A: A C D E G.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '♭3', '4', '5', '♭7', '8'],
          steps: ['W+H', 'W', 'W', 'W+H', 'W'],
        },
        audio: [69, 72, 74, 76, 79, 81],
        references: [
          'Smoke on the Water (Deep Purple)',
          'Sunshine of Your Love (Cream)',
          "Most rock and blues guitar solos",
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'A minor pentatonic up.',
        notes: [69, 72, 74, 76, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'The same on the way back.',
        notes: [81, 79, 76, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bluesy lick',
        description: 'Pentatonic minor used in a typical lick — short phrase that returns to the root.',
        notes: [76, 79, 81, 79, 76, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Solo phrase',
        description: 'A longer melodic phrase a guitarist or vocalist might improvise over a minor groove.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72, 76, 79, 81, 79],
        style: 'melody',
      },
    ],
  },
  {
    id: 'pentatonic-major',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Pentatonic Major',
    summary: 'Major\'s five-note cousin. The bedrock of country, gospel and Brazilian folk.',
    steps: [
      {
        type: 'theory',
        title: 'Drop the half steps',
        text: `Major pentatonic removes the 4th and 7th from the major scale: <strong>1 2 3 5 6</strong>. No half steps means almost every combination sounds consonant — perfect for vocal melodies and singalongs. In C: C D E G A.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '3', '5', '6', '8'],
          steps: ['W', 'W', 'W+H', 'W', 'W+H'],
        },
        audio: [60, 62, 64, 67, 69, 72],
        references: [
          'Amazing Grace — pentatonic major',
          'My Girl (The Temptations)',
          'Brazilian sambas often pivot on it',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Climb C major pentatonic.',
        notes: [60, 62, 64, 67, 69, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'And down again.',
        notes: [72, 69, 67, 64, 62, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Country lick',
        description: 'A typical country/folk melodic phrase that lives entirely in the pentatonic.',
        notes: [60, 64, 67, 69, 67, 64, 62, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Brazilian-flavoured phrase',
        description: 'A laid-back melody — characteristic of Brazilian popular music.',
        notes: [62, 64, 67, 69, 64, 67, 69, 72, 69, 67],
        style: 'melody',
      },
    ],
  },
  {
    id: 'blues-scale',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Blues Scale',
    summary: 'Pentatonic minor plus a "blue note" — the soul of blues, jazz and rock.',
    steps: [
      {
        type: 'theory',
        title: 'The blue note',
        text: `The blues scale adds a chromatic note between the 4th and 5th of pentatonic minor — the famous <strong>♭5</strong> or "blue note": <strong>1 ♭3 4 ♭5 5 ♭7</strong>. That extra chromatic step gives the scale its iconic tension. In A: A C D E♭ E G.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '♭3', '4', '♭5', '5', '♭7', '8'],
          steps: ['W+H', 'W', 'H', 'H', 'W+H', 'W'],
        },
        audio: [69, 72, 74, 75, 76, 79, 81],
        references: [
          'Sweet Home Chicago (Robert Johnson)',
          "Pride and Joy (Stevie Ray Vaughan)",
          'Almost any 12-bar blues solo',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Hear that blue note slide between the 4th and 5th.',
        notes: [69, 72, 74, 75, 76, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'Down through the blue note again.',
        notes: [81, 79, 76, 75, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Classic blues lick',
        description: 'A signature licks that bends through the blue note.',
        notes: [76, 79, 81, 79, 76, 75, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Call & response phrase',
        description: 'A two-part melodic statement — the call goes up, the response answers down.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72, 75, 74, 72, 69],
        style: 'melody',
      },
    ],
  },
  {
    id: 'harmonic-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Harmonic Minor',
    summary: 'Natural minor with a raised 7th. Exotic, dramatic — the heart of flamenco and metal.',
    steps: [
      {
        type: 'theory',
        title: 'Raise the leading tone',
        text: `Harmonic minor takes natural minor and lifts the 7th degree by a half step: <strong>1 2 ♭3 4 5 ♭6 7</strong>. The big augmented-second leap between ♭6 and 7 gives the scale its dramatic, slightly Middle-Eastern flavour, and the raised 7 functions as a leading tone — the reason it was invented for harmony in the first place.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '♭3', '4', '5', '♭6', '7', '8'],
          steps: ['W', 'H', 'W', 'W', 'H', 'W+H', 'H'],
        },
        audio: [69, 71, 72, 74, 76, 77, 80, 81],
        references: [
          'Flamenco music — its native idiom',
          'Hava Nagila (traditional)',
          'Yngwie Malmsteen — neoclassical metal solos',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending in A',
        description: 'Watch out for the augmented 2nd between the 6th and 7th — it sounds exotic.',
        notes: [69, 71, 72, 74, 76, 77, 80, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending in A',
        description: 'Coming back through that big leap.',
        notes: [81, 80, 77, 76, 74, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Flamenco-style phrase',
        description: 'A dramatic melodic phrase that evokes Spanish music.',
        notes: [69, 72, 76, 77, 80, 77, 76, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Classical mini-phrase',
        description: 'The leading tone resolves up to the tonic — the foundation of harmonic-minor harmony.',
        notes: [76, 77, 80, 81, 80, 77, 76, 72, 69, 80, 81],
        style: 'melody',
      },
    ],
  },
  {
    id: 'greek-modes',
    group: 'Scales',
    tag: 'Theory · Modes',
    title: 'Greek Modes',
    summary: 'Seven modes, one parent scale. Each one has its own colour.',
    steps: [
      {
        type: 'theory',
        title: 'Modes are starting points',
        text: `The seven Greek modes are obtained by playing the major scale starting from each of its degrees. Same notes, different tonic — and therefore a different feel. Ionian (1) is plain major; Aeolian (6) is natural minor. The four below are the most expressive non-diatonic colours.`,
      },
      {
        type: 'exercise',
        title: 'Dorian (D from C major)',
        description: 'Minor with a raised 6th. Jazzy and slightly hopeful.',
        notes: [62, 64, 65, 67, 69, 71, 72, 74],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Phrygian (E from C major)',
        description: 'Minor with a flat 2nd. Dark, Spanish/Middle-Eastern colour.',
        notes: [64, 65, 67, 69, 71, 72, 74, 76],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lydian (F from C major)',
        description: 'Major with a raised 4th. Floating, dreamy quality.',
        notes: [65, 67, 69, 71, 72, 74, 76, 77],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixolydian (G from C major)',
        description: 'Major with a flat 7th. Dominant, bluesy.',
        notes: [67, 69, 71, 72, 74, 76, 77, 79],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Dorian melody',
        description: 'Short tune highlighting the Dorian raised 6th — the colour that distinguishes it from natural minor.',
        notes: [62, 65, 67, 65, 64, 65, 67, 69, 67, 65],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lydian melody',
        description: 'Phrase that leans on the raised 4th — Lydian\'s signature dreamy lift.',
        notes: [65, 67, 71, 72, 71, 67, 71, 65],
        style: 'melody',
      },
    ],
  },
  // ============== CHALLENGE 1 ==============
  {
    id: 'challenge-scales',
    group: 'Challenges',
    tag: 'Challenge · Scales',
    title: 'Scales challenge',
    summary: 'Mix major, natural minor, pentatonic and modes. Identify the colour by ear.',
    steps: [
      {
        type: 'theory',
        title: 'The drill',
        text: `Three short licks below — each one comes from a different scale family covered earlier. Listen, then sing or play it back. By the third one your ear should already be identifying the mode without thinking.`,
      },
      {
        type: 'exercise',
        title: 'Mystery #1',
        description: 'Major or minor? Listen and play back.',
        notes: [60, 64, 67, 72, 67, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mystery #2',
        description: 'A flavour of one of the modes.',
        notes: [62, 65, 67, 69, 65, 62, 64, 62],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mystery #3',
        description: 'Pentatonic territory.',
        notes: [69, 76, 79, 76, 72, 74, 72, 69],
        style: 'melody',
      },
    ],
  },
  // ================= CHORDS =================
  {
    id: 'major-triad',
    group: 'Chords',
    tag: 'Theory · Chords',
    title: 'Major Triad & Inversions',
    summary: 'Root, 3rd, 5th — and the same chord stacked three different ways.',
    steps: [
      {
        type: 'theory',
        title: 'The three positions',
        text: `A triad is three notes: root, 3rd, 5th. Reorder them and you get the same chord with a different bottom note. <strong>Root position</strong>: 1-3-5. <strong>1st inversion</strong>: 3-5-1. <strong>2nd inversion</strong>: 5-1-3. The chord is still C major in all three — but the bass shifts the colour and the voice-leading possibilities.`,
      },
      {
        type: 'exercise',
        title: 'Root position — C E G',
        description: 'Bottom-up stacking: the root is in the bass.',
        notes: [60, 64, 67],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '1st inversion — E G C',
        description: 'Same chord with the 3rd in the bass. Sounds slightly less stable, often used as a passing voicing.',
        notes: [64, 67, 72],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '2nd inversion — G C E',
        description: '5th in the bass. Common as a cadential 6/4 chord before resolving.',
        notes: [67, 72, 76],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Triad melody',
        description: 'A bouncing melodic line that lives entirely on the C major triad notes.',
        notes: [60, 64, 67, 64, 60, 67, 72, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Triad with passing tones',
        description: 'Triad notes connected by the scale steps in between. Common building block of melodies.',
        notes: [60, 62, 64, 65, 67, 65, 64, 60],
        style: 'melody',
      },
    ],
  },
  {
    id: 'minor-triad',
    group: 'Chords',
    tag: 'Theory · Chords',
    title: 'Minor Triad & Inversions',
    summary: 'Same idea, flatter 3rd. Darker mood.',
    steps: [
      {
        type: 'theory',
        title: 'Flatten the 3rd',
        text: `A minor triad lowers the major's 3rd by a semitone: <strong>1 ♭3 5</strong>. In A minor: A C E. The same three inversions (root / 1st / 2nd) apply. Stacking and rearranging unlocks rich voice-leading without changing the chord's identity.`,
      },
      {
        type: 'exercise',
        title: 'Root position — A C E',
        description: 'The "anchor" voicing.',
        notes: [69, 72, 76],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '1st inversion — C E A',
        description: '3rd in the bass.',
        notes: [72, 76, 81],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '2nd inversion — E A C',
        description: '5th in the bass.',
        notes: [76, 81, 84],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Minor triad melody',
        description: 'A melodic phrase that outlines the A minor triad — moody, contemplative.',
        notes: [69, 72, 76, 72, 69, 76, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Triad with neighbours',
        description: 'Triad notes ornamented with chromatic neighbour tones.',
        notes: [72, 71, 72, 76, 75, 76, 81, 76],
        style: 'melody',
      },
    ],
  },
  {
    id: 'tetrads',
    group: 'Chords',
    tag: 'Theory · Tetrads',
    title: 'Tetrads (7th chords)',
    summary: 'Add a fourth note on top of the triad — the doorway into jazz harmony.',
    steps: [
      {
        type: 'theory',
        title: 'Adding the 7th',
        text: `A <strong>tetrad</strong> stacks four notes a third apart: 1-3-5-7. The 7th gives the chord new colours: <strong>major 7</strong> (raised 7) is dreamy and bright; <strong>dominant 7</strong> (♭7) wants to resolve and is the workhorse of blues and jazz; <strong>minor 7</strong> (♭3, ♭7) is soulful. Most jazz lead sheets are written in 7th chords.`,
      },
      {
        type: 'exercise',
        title: 'C major 7 chord',
        description: 'C - E - G - B. The major 7th sits a half-step below the octave.',
        notes: [60, 64, 67, 71],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'C dominant 7',
        description: 'Lower the 7th by a semitone (C - E - G - B♭). Bluesy, restless — typically resolves down a fifth.',
        notes: [60, 64, 67, 70],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'C minor 7',
        description: 'C - E♭ - G - B♭. Smooth, soulful colour — the harmonic backbone of countless ballads.',
        notes: [60, 63, 67, 70],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Cmaj7 arpeggio melody',
        description: 'A melodic line outlining the major 7 chord — climbs the chord and resolves down to the root.',
        notes: [60, 64, 67, 71, 72, 71, 67, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bebop-flavoured 7th line',
        description: 'A melody that traces a dominant 7 arpeggio and resolves down a half-step — the bebop way to land on a chord change.',
        notes: [55, 59, 62, 65, 64, 60, 64, 67, 71, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'ii–V–I in 7ths',
        description: 'The iconic jazz cadence with seventh chords: Dm7 → G7 → Cmaj7. The harmonic engine of bebop.',
        notes: [
          [62, 65, 69, 72],
          [55, 59, 62, 65],
          [60, 64, 67, 71],
        ],
        style: 'progression',
      },
    ],
  },
  {
    id: 'arpeggios',
    group: 'Chords',
    tag: 'Theory · Arpeggios',
    title: 'Arpeggios',
    summary: 'A chord, but one note at a time. Bridge between chords and melody.',
    steps: [
      {
        type: 'theory',
        title: 'What is an arpeggio?',
        text: `Take any chord and play its notes one after another instead of together — that's an arpeggio. They're how melodies "imply" the harmony underneath. Singers use them to outline chord changes; bass lines walk through them.`,
      },
      {
        type: 'exercise',
        title: 'C major arpeggio (1-3-5-8)',
        description: 'Outline the major triad note-by-note up to the octave.',
        notes: [60, 64, 67, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'A minor arpeggio',
        description: 'Same shape, minor flavour.',
        notes: [69, 72, 76, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'C major 7 arpeggio',
        description: 'Add the major 7th (B) for a jazzy colour.',
        notes: [60, 64, 67, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Arpeggio melody',
        description: 'A melodic line built almost entirely on arpeggio notes — outlines the harmony without ever stating a chord.',
        notes: [60, 64, 67, 64, 67, 72, 67, 64, 60],
        style: 'melody',
      },
    ],
  },
  // ============== CHALLENGE 2 ==============
  {
    id: 'challenge-chords',
    group: 'Challenges',
    tag: 'Challenge · Chords',
    title: 'Chords challenge',
    summary: 'Triads, inversions and arpeggios from previous modules — mixed.',
    steps: [
      {
        type: 'exercise',
        title: 'Voicing #1',
        description: 'Hear the chord — can you tell major or minor, and which inversion?',
        notes: [64, 67, 72],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Voicing #2',
        description: 'Another voicing. Notice the bass note.',
        notes: [76, 81, 84],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Arpeggio chain',
        description: 'Two arpeggios in a row — major then minor.',
        notes: [60, 64, 67, 72, 69, 72, 76, 81],
        style: 'melody',
      },
    ],
  },
  // ================= HARMONY: PROGRESSIONS =================
  {
    id: 'prog-i-v-vi-iv',
    group: 'Progressions',
    tag: 'Progressions · Pop',
    title: 'I–V–vi–IV (Pop axis)',
    summary: 'The most popular progression in modern pop. Instantly familiar.',
    steps: [
      {
        type: 'theory',
        title: 'The "axis of awesome"',
        text: `Each chord drops or lifts the harmonic tension by exactly the right amount: <strong>I</strong> (home) → <strong>V</strong> (suspense) → <strong>vi</strong> (twist into minor) → <strong>IV</strong> (gentle return). In C major: C, G, Am, F.`,
        diagram: { type: 'progression', chords: ['I', 'V', 'vi', 'IV'] },
        audio: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [65, 69, 72]],
        audioStyle: 'progression',
        references: [
          "Let It Be (The Beatles)",
          "Don't Stop Believin' (Journey)",
          'Someone Like You (Adele)',
          'With or Without You (U2)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        description: 'Play and feel each chord land.',
        notes: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [65, 69, 72]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody outlining the chords',
        description: 'A simple pop melody that lands on a chord tone over each new chord.',
        notes: [60, 64, 67, 71, 67, 71, 74, 71, 69, 72, 76, 72, 65, 69, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Riff over the loop',
        description: 'A repeating melodic riff that fits all four chords — typical pop topline.',
        notes: [64, 67, 64, 67, 71, 74, 71, 67, 69, 72, 69, 65, 65, 69, 72, 65],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-50s',
    group: 'Progressions',
    tag: 'Progressions · 50s',
    title: 'I–vi–IV–V (50s doo-wop)',
    summary: 'The "Stand by Me" loop. Defines an entire era of pop.',
    steps: [
      {
        type: 'theory',
        title: 'The doo-wop circle',
        text: `Take I, drop to vi, slide to IV, finish on V — and repeat. The vi keeps the major-key feel while adding a touch of melancholy; V then sets up the return to I. In C: C – Am – F – G.`,
        diagram: { type: 'progression', chords: ['I', 'vi', 'IV', 'V'] },
        audio: [[60, 64, 67], [69, 72, 76], [65, 69, 72], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Stand by Me (Ben E. King)',
          'Earth Angel (The Penguins)',
          "Heart and Soul (Hoagy Carmichael)",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        description: 'C – Am – F – G in slow motion.',
        notes: [[60, 64, 67], [69, 72, 76], [65, 69, 72], [67, 71, 74]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody over the loop',
        description: 'A typical 50s vocal melody.',
        notes: [60, 64, 67, 64, 69, 72, 69, 64, 65, 69, 72, 69, 67, 71, 74, 71],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bass walk between chords',
        description: 'Stepwise bass connecting each chord root.',
        notes: [48, 52, 55, 57, 60, 57, 53, 55],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-12-bar-blues',
    group: 'Progressions',
    tag: 'Progressions · Blues',
    title: '12-bar Blues',
    summary: 'I, IV, V — the universal blueprint of blues, R&B, rock and jazz.',
    steps: [
      {
        type: 'theory',
        title: 'Twelve bars, three chords',
        text: `The blues form is twelve bars long: <strong>I I I I · IV IV I I · V IV I V</strong>. Three chords, infinite variations. With dominant-7 chords on every degree, you've got the foundation of blues, soul, jazz, country and rock & roll.`,
        diagram: { type: 'progression', chords: ['I7', 'IV7', 'I7', 'V7', 'IV7', 'I7'] },
        audio: [[60, 64, 67, 70], [65, 69, 72, 75], [60, 64, 67, 70], [67, 71, 74, 77], [65, 69, 72, 75], [60, 64, 67, 70]],
        audioStyle: 'progression',
        references: [
          'Sweet Home Chicago (Robert Johnson)',
          'Crossroads (Cream)',
          'Pride and Joy (Stevie Ray Vaughan)',
          'Boogie Woogie (any of the classics)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the basic 12-bar (condensed)',
        description: 'Six chords summarising the form.',
        notes: [
          [60, 64, 67, 70], [65, 69, 72, 75], [60, 64, 67, 70],
          [67, 71, 74, 77], [65, 69, 72, 75], [60, 64, 67, 70],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Blues solo line',
        description: 'A classic 12-bar improvisation outline using the blues scale over each chord.',
        notes: [69, 72, 74, 75, 76, 79, 76, 75, 74, 72, 69, 67, 69, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking blues bassline',
        description: 'A walking bass line that hits chord tones over each bar of the form.',
        notes: [48, 52, 55, 57, 53, 57, 60, 62, 48, 52, 55, 57, 55, 59, 62, 64, 53, 57, 60, 62, 48, 52, 55, 57],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-ii-v-i',
    group: 'Progressions',
    tag: 'Progressions · Jazz',
    title: 'ii–V–I (Jazz cadence)',
    summary: "The most important progression in jazz. Resolves home in two perfect 5ths.",
    steps: [
      {
        type: 'theory',
        title: 'Two falling fifths',
        text: `<strong>ii–V–I</strong> creates the strongest harmonic resolution in tonal music: each chord root falls a perfect fifth into the next. With 7th chords (Dm7 → G7 → Cmaj7) you've got the central building block of jazz harmony.`,
        diagram: { type: 'progression', chords: ['ii7', 'V7', 'Imaj7'] },
        audio: [[62, 65, 69, 72], [55, 59, 62, 65], [60, 64, 67, 71]],
        audioStyle: 'progression',
        references: [
          'Autumn Leaves',
          'All The Things You Are',
          "Almost any jazz standard's last 4 bars",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear ii–V–I in 7ths',
        description: 'Dm7 → G7 → Cmaj7. Feel the falling 5ths in the bass.',
        notes: [[62, 65, 69, 72], [55, 59, 62, 65], [60, 64, 67, 71]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Bebop melody',
        description: 'A short bebop-style line that outlines each chord on its strong beats.',
        notes: [62, 65, 69, 72, 71, 67, 65, 62, 60, 64, 67, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Guide-tone line',
        description: 'Just the 3rds and 7ths of each chord — the core of any jazz melody.',
        notes: [65, 72, 65, 71, 64, 71],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-andalusian',
    group: 'Progressions',
    tag: 'Progressions · Spanish',
    title: 'Andalusian Cadence (i–VII–VI–V)',
    summary: 'A descending bass line in minor that defines flamenco and Spanish music.',
    steps: [
      {
        type: 'theory',
        title: 'The Phrygian descent',
        text: `Starting on minor i, the bass walks down in stepwise motion: <strong>i → VII → VI → V</strong>. The arrival on V (a major chord!) gives it that haunting Spanish/Phrygian flavour. In A minor: Am – G – F – E.`,
        diagram: { type: 'progression', chords: ['i', 'VII', 'VI', 'V'] },
        audio: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [52, 56, 59]],
        audioStyle: 'progression',
        references: [
          'Hit the Road Jack (Ray Charles)',
          'Sultans of Swing (Dire Straits) — coda',
          'Almost any flamenco piece',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the cadence',
        description: 'Am – G – F – E.',
        notes: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [52, 56, 59]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Spanish-flavoured melody',
        description: 'Phrygian-flavoured melodic line over the descent.',
        notes: [69, 72, 76, 72, 67, 71, 65, 69, 64, 67, 65, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending bass line',
        description: 'Just the bass walk down — feel its inevitability.',
        notes: [57, 55, 53, 52],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-pachelbel',
    group: 'Progressions',
    tag: 'Progressions · Classical',
    title: 'Pachelbel (I–V–vi–iii–IV–I–IV–V)',
    summary: "Canon in D. Eight chords that have powered hits from Bach to Coolio.",
    steps: [
      {
        type: 'theory',
        title: 'Eight chords, endless songs',
        text: `Pachelbel's Canon descends through almost every diatonic chord in the key, then climbs back to V. The descending bass line (D-A-B-F#-G-D-G-A in D major) is irresistibly catchy and has been reused in pop and rock for centuries.`,
        diagram: { type: 'progression', chords: ['I', 'V', 'vi', 'iii', 'IV', 'I', 'IV', 'V'] },
        audio: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [64, 67, 71], [65, 69, 72], [60, 64, 67], [65, 69, 72], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Canon in D (Pachelbel)',
          'Basket Case (Green Day)',
          'C U When U Get There (Coolio)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the canon progression',
        description: 'All 8 chords in C.',
        notes: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [64, 67, 71], [65, 69, 72], [60, 64, 67], [65, 69, 72], [67, 71, 74]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Canon-style melody',
        description: "A simple counter-melody woven over the harmony.",
        notes: [72, 71, 69, 67, 65, 64, 65, 67, 65, 67, 65, 64, 65, 67, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending bass walk',
        description: 'The signature descending bass line through all 8 chords.',
        notes: [48, 55, 57, 52, 53, 48, 53, 55],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-vi-iv-i-v',
    group: 'Progressions',
    tag: 'Progressions · Modern Pop',
    title: 'vi–IV–I–V (Sad pop)',
    summary: 'The "axis" rotated to start on the relative minor — modern emotional pop.',
    steps: [
      {
        type: 'theory',
        title: 'Same chords, different gravity',
        text: `Same four chords as I–V–vi–IV but starting on vi makes the listener hear the song in the relative minor at first, before the IV–I "turn around" lifts the mood. In C: Am – F – C – G.`,
        diagram: { type: 'progression', chords: ['vi', 'IV', 'I', 'V'] },
        audio: [[69, 72, 76], [65, 69, 72], [60, 64, 67], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          "Apologize (OneRepublic)",
          "Numb (Linkin Park)",
          "Save Yourself (Kaleo)",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        notes: [[69, 72, 76], [65, 69, 72], [60, 64, 67], [67, 71, 74]],
        style: 'progression',
        description: 'Am – F – C – G.',
      },
      {
        type: 'exercise',
        title: 'Singable topline',
        description: 'A melody that opens with a yearning minor and resolves up.',
        notes: [69, 72, 76, 72, 65, 69, 72, 69, 60, 64, 67, 64, 67, 71, 74, 71],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Counter-melody',
        description: 'A melodic counter-line that lifts from the minor into the IV resolution.',
        notes: [69, 72, 74, 76, 65, 67, 69, 72, 60, 62, 64, 67, 67, 71, 74, 76],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-minor-loop',
    group: 'Progressions',
    tag: 'Progressions · Minor',
    title: 'i–VII–VI–VII (Minor rock loop)',
    summary: 'Heavy, modal — the engine of countless rock and metal anthems.',
    steps: [
      {
        type: 'theory',
        title: 'Modal minor rock',
        text: `Stay in minor, treat the V as VII (a flat 7) — and you've got pure Aeolian rock. The progression has gravitas without ever using the leading tone, which keeps it grounded and earthy.`,
        diagram: { type: 'progression', chords: ['i', 'VII', 'VI', 'VII'] },
        audio: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [55, 59, 62]],
        audioStyle: 'progression',
        references: [
          'Stairway to Heaven (Led Zeppelin) — verse',
          'Mad World (Tears for Fears / Gary Jules)',
          'Numb (Linkin Park)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the loop',
        description: 'Am – G – F – G.',
        notes: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [55, 59, 62]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Riff over the loop',
        description: 'A pentatonic-minor riff that grooves over all four chords.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Melodic counter-line',
        description: 'A vocal-style line that rises and falls over the harmony.',
        notes: [69, 72, 76, 72, 71, 67, 65, 67, 65, 64, 67, 65],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-royal-road',
    group: 'Progressions',
    tag: 'Progressions · J-Pop',
    title: 'Royal Road (IV–V–iii–vi)',
    summary: 'The sound of anime openings and modern J-pop.',
    steps: [
      {
        type: 'theory',
        title: 'Climb and resolve',
        text: `IV–V–iii–vi pushes upward (IV–V) then reflects (iii–vi) — like a question and a thoughtful answer. In Japanese pop it's so common it has its own name: "ouhouto", the Royal Road. In C: F – G – Em – Am.`,
        diagram: { type: 'progression', chords: ['IV', 'V', 'iii', 'vi'] },
        audio: [[65, 69, 72], [67, 71, 74], [64, 67, 71], [69, 72, 76]],
        audioStyle: 'progression',
        references: [
          'Cruel Angel\'s Thesis (Neon Genesis Evangelion)',
          'Pretender (Official Hige Dandism)',
          'Lemon (Kenshi Yonezu)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the loop',
        description: 'F – G – Em – Am.',
        notes: [[65, 69, 72], [67, 71, 74], [64, 67, 71], [69, 72, 76]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'J-pop topline',
        description: 'A bright, climbing vocal line.',
        notes: [65, 69, 72, 74, 67, 71, 74, 76, 67, 71, 74, 71, 69, 72, 76, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Anime-style counter-line',
        description: 'A descending counter-line that fits the climb of the topline.',
        notes: [76, 74, 72, 71, 76, 74, 72, 71, 71, 67, 69, 71, 76, 74, 72, 69],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-circle-fifths',
    group: 'Progressions',
    tag: 'Progressions · Circle of 5ths',
    title: 'Circle of 5ths walk',
    summary: 'Falling 5ths in sequence — the gear-train that drives jazz standards forward.',
    steps: [
      {
        type: 'theory',
        title: 'Down a 5th, every chord',
        text: `Each chord's root falls a perfect 5th into the next. Played around the whole circle: C → F → B♭ → E♭ → A♭ … back to C. Found in dozens of jazz standards as their backbone — short fragments give endless forward motion.`,
        diagram: { type: 'progression', chords: ['I7', 'IV7', '♭VII7', '♭III7', '♭VI7'] },
        audio: [[60, 64, 67, 70], [65, 69, 72, 75], [58, 62, 65, 68], [63, 67, 70, 73], [56, 60, 63, 66]],
        audioStyle: 'progression',
        references: [
          'Autumn Leaves',
          'Fly Me to the Moon',
          'I Will Survive (the chorus)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear five falling 5ths',
        description: 'Each root drops by a perfect 5th.',
        notes: [[60, 64, 67, 70], [65, 69, 72, 75], [58, 62, 65, 68], [63, 67, 70, 73], [56, 60, 63, 66]],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody over the cycle',
        description: 'A line that lands on the chord 3rd at every change.',
        notes: [64, 67, 70, 64, 69, 72, 75, 69, 62, 65, 68, 62, 67, 70, 73, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking-bass cycle',
        description: 'The bass line walking through the same falling 5ths.',
        notes: [60, 64, 67, 70, 65, 69, 72, 70, 58, 62, 65, 63, 63, 67, 70, 68],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-blues-turnaround',
    group: 'Progressions',
    tag: 'Progressions · Blues',
    title: 'Blues turnaround',
    summary: 'The 4-bar phrase that sets up the next chorus of a blues. Pure DNA of the form.',
    steps: [
      {
        type: 'theory',
        title: 'The last four bars',
        text: `A blues turnaround is the I → V → I (or I → IV → I → V) phrase at the end of every 12-bar chorus. The walking bass line and the chromatic descent in the chord voicings are its signature.`,
        diagram: { type: 'progression', chords: ['I', 'IV', 'I', 'V'] },
        audio: [[48, 60, 64, 67], [53, 65, 69, 72], [48, 60, 64, 67], [55, 67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Sweet Home Chicago — last four bars of every chorus',
          'I Got My Mojo Working',
          "Every blues you've ever heard",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the turnaround',
        notes: [[48, 60, 64, 67], [53, 65, 69, 72], [48, 60, 64, 67], [55, 67, 71, 74]],
        style: 'progression',
        description: 'C – F – C – G.',
      },
      {
        type: 'exercise',
        title: 'Walking turnaround bassline',
        description: 'The classic walking-bass turnaround.',
        notes: [48, 50, 52, 53, 55, 53, 52, 50, 48, 50, 52, 55, 53, 55, 56, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lick that resolves home',
        description: "A blues guitar lick over the turnaround.",
        notes: [76, 79, 81, 79, 76, 75, 74, 72, 69, 67, 69, 72],
        style: 'melody',
      },
    ],
  },
  // ================= BASS =================
  {
    id: 'walking-bass',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking Bass — Foundations',
    summary: 'Quarter notes per beat, landing on chord roots. The starting point.',
    steps: [
      {
        type: 'theory',
        title: 'The walking principle',
        text: `In a walking bass line each beat gets a quarter note. Beat 1 lands on the <strong>chord root</strong>, beat 3 typically on the <strong>5th</strong> or <strong>3rd</strong>, and beats 2 and 4 are <strong>connectors</strong> — scale or chromatic notes that lead the ear smoothly into the next chord.`,
        audio: [48, 52, 55, 60, 67, 64, 60, 55],
        references: [
          'Ray Brown (Oscar Peterson Trio)',
          'Paul Chambers (Miles Davis)',
          "Almost any swing-era jazz recording",
        ],
      },
      {
        type: 'exercise',
        title: 'Roots only',
        description: 'Just chord roots — the simplest walking line.',
        notes: [48, 48, 48, 48, 53, 53, 53, 53, 55, 55, 55, 55, 48, 48, 48, 48],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Roots + 5ths',
        description: 'Add the 5th on beat 3 — the second most stable note.',
        notes: [48, 55, 48, 55, 53, 60, 53, 60, 55, 62, 55, 62, 48, 55, 48, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Adding the 3rd',
        description: 'Beat 3 = 3rd of the chord. Adds chord colour.',
        notes: [48, 52, 55, 52, 53, 57, 60, 57, 55, 59, 62, 59, 48, 52, 55, 52],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-diatonic',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Diatonic Walks',
    summary: 'Use scale steps to connect roots — the staple of mainstream jazz bass lines.',
    steps: [
      {
        type: 'theory',
        title: 'Stepwise connection',
        text: `The most natural walking bass uses <strong>scale tones</strong> (notes in the key) to bridge chord roots. Each pair of bars is a small puzzle: you've got 4 beats, the next chord arrives on beat 5, and you need beats 1–4 to land on chord tones with smooth motion.`,
        audio: [48, 50, 52, 53, 53, 55, 57, 55, 55, 53, 52, 50, 48, 50, 52, 55],
        references: [
          'Autumn Leaves',
          'Blue Bossa',
        ],
      },
      {
        type: 'exercise',
        title: 'Walking up',
        description: 'Stepwise climb: 1 → 2 → 3 → 4 → land on IV chord root.',
        notes: [48, 50, 52, 53, 53, 55, 57, 59, 60, 59, 57, 55, 53, 52, 50, 48],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking down',
        description: 'Descending diatonic walk over I → vi → IV → V.',
        notes: [60, 59, 57, 55, 57, 55, 53, 52, 53, 52, 50, 48, 55, 53, 52, 50],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walk + arpeggio mix',
        description: 'Mix scale steps with chord tones for variety.',
        notes: [48, 52, 55, 53, 53, 57, 60, 59, 55, 59, 62, 60, 48, 50, 52, 55],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-chromatic',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Chromatic Approach Notes',
    summary: 'A half-step into the next chord root makes any walk sound like jazz.',
    steps: [
      {
        type: 'theory',
        title: 'Land a half-step away',
        text: `The single biggest "jazz move" in walking bass: precede each chord root with a <strong>chromatic neighbour</strong> — a half-step above or below. It heightens the resolution at every bar line. With chromatic approach from below: ...root, 3rd, 5th, ♭root-of-next.`,
        audio: [48, 52, 55, 56, 53, 57, 60, 54, 55, 59, 62, 56, 48, 52, 55, 56],
        references: [
          'Ray Brown — every record he made',
          "Walter Page (Count Basie's bassist)",
        ],
      },
      {
        type: 'exercise',
        title: 'Approach from below',
        description: 'Last beat is one half-step below the next chord root.',
        notes: [48, 52, 55, 52, 53, 57, 60, 54, 55, 59, 62, 56, 48, 52, 55, 47],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Approach from above',
        description: 'Last beat is one half-step above the next root.',
        notes: [48, 52, 55, 54, 53, 57, 60, 56, 55, 59, 62, 49, 48, 52, 55, 49],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixed approach (above & below)',
        description: 'Alternate the direction for more variety.',
        notes: [48, 52, 55, 54, 53, 57, 60, 56, 55, 59, 62, 60, 48, 50, 52, 47],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-fifths',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking through the Cycle of 5ths',
    summary: 'Iconic patterns over jazz standards driven by falling 5ths.',
    steps: [
      {
        type: 'theory',
        title: 'Cycle in the bass',
        text: `Many jazz tunes have stretches where roots fall by 5ths (Cmaj7 → F7 → B♭maj7 → E♭7 …). Bassists love these because the line writes itself: root → 3rd → 5th → chromatic into next root. Pure forward motion.`,
        audio: [60, 64, 67, 70, 65, 69, 72, 75, 58, 62, 65, 68, 63, 67, 70, 73],
        references: [
          'All The Things You Are (the bridge)',
          'Autumn Leaves',
          'Sweet Georgia Brown',
        ],
      },
      {
        type: 'exercise',
        title: 'Five chords down a 5th each',
        description: 'Walking through five 7th chords, each root a 5th below the last.',
        notes: [60, 64, 67, 70, 65, 69, 72, 75, 58, 62, 65, 68, 63, 67, 70, 73, 56, 60, 63, 66],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Cycle with chromatic approach',
        description: 'Same cycle, with a half-step approach into each new root.',
        notes: [60, 64, 67, 66, 65, 69, 72, 71, 70, 62, 65, 64, 63, 67, 70, 69, 68, 60, 63, 66],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-inversions',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Inversions — 3rd & 5th in the Bass',
    summary: 'Land on chord tones other than the root for richer voice-leading.',
    steps: [
      {
        type: 'theory',
        title: 'You don\'t have to start on the root',
        text: `Every walking line doesn't need to land on the root every bar. Landing on the <strong>3rd</strong> (1st inversion in the bass) keeps the line moving smoothly between distant roots; landing on the <strong>5th</strong> (2nd inversion) creates suspension and pull.`,
        audio: [52, 55, 57, 60, 57, 60, 62, 65, 53, 55, 57, 60, 48, 52, 55, 57],
        references: [
          'Bill Evans Trio — bassist Scott LaFaro famously avoided roots',
          'Charles Mingus — chord-tone bass lines',
        ],
      },
      {
        type: 'exercise',
        title: '3rd in the bass',
        description: 'Each chord begins with its 3rd in the bass.',
        notes: [52, 55, 60, 55, 57, 60, 65, 60, 59, 62, 67, 62, 52, 55, 60, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: '5th in the bass',
        description: 'Walking with each bar starting on the chord 5th.',
        notes: [55, 60, 64, 60, 60, 65, 69, 65, 62, 67, 71, 67, 55, 60, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixing positions',
        description: 'Alternate root, 3rd, 5th over four chords for a flowing line.',
        notes: [48, 52, 55, 52, 57, 60, 65, 60, 50, 53, 57, 53, 55, 59, 62, 59],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-doubletime',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Double-time & Syncopation',
    summary: 'Two notes per beat or pushed accents — adds urgency and groove.',
    steps: [
      {
        type: 'theory',
        title: 'Doubling the rhythm',
        text: `When the harmony is slow, walking bassists often double-time — eighth notes instead of quarters — to keep the pulse alive. <strong>Syncopation</strong> (anticipating beats by an eighth) adds groove: try landing on the "and" of beat 4 to push into the next bar.`,
        audio: [48, 50, 52, 50, 53, 52, 50, 48, 53, 55, 57, 55, 60, 59, 57, 55],
        references: [
          'Ron Carter (Miles Davis 60s quintet)',
          'Christian McBride',
        ],
      },
      {
        type: 'exercise',
        title: 'Double-time walk',
        description: 'Eighth-note walk over the same chords. Twice the notes, same harmony.',
        notes: [48, 50, 52, 53, 50, 52, 53, 55, 53, 55, 57, 59, 55, 57, 59, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Syncopated push',
        description: "Anticipates each chord change by an eighth note (the 'and' of 4).",
        notes: [48, 52, 55, 52, 53, 53, 57, 60, 53, 60, 55, 62, 55, 55, 50, 48],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walk with rests',
        description: 'Quarter-rest in beat 2 — gives the line breathing room.',
        notes: [48, 55, 60, 53, 57, 60, 55, 62, 60, 48, 55, 53],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-triplets',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Triplets & Shuffle',
    summary: 'The swung triplet is the soul of jazz feel and shuffled blues.',
    steps: [
      {
        type: 'theory',
        title: 'Three notes per beat',
        text: `In a shuffle or swing groove, eighth notes are felt as the first and third of a triplet — long-short, long-short. Walking bassists use this to add tension fills (an entire triplet on beat 4) that propel into the next bar.`,
        audio: [48, 50, 52, 53, 55, 57, 53, 55, 57, 60, 62, 64, 60, 64, 65, 67],
        references: [
          'Boogie-woogie pianists',
          'Blues bassists like Willie Dixon',
        ],
      },
      {
        type: 'exercise',
        title: 'Triplet on beat 4',
        description: 'Quarters on 1-2-3, then a triplet fill on beat 4 leading into the next chord.',
        notes: [48, 52, 55, 53, 55, 57, 53, 57, 60, 59, 60, 62, 55, 60, 62, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Shuffle bass pattern',
        description: 'A classic boogie-shuffle bass: root, 3rd, 5th, 6th, ♭7, 6th, 5th, 3rd.',
        notes: [48, 52, 55, 57, 58, 57, 55, 52, 53, 57, 60, 62, 63, 62, 60, 57],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-blues',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking the 12-bar Blues',
    summary: "A full chorus of walking bass over the blues. Classic Saturday-night sound.",
    steps: [
      {
        type: 'theory',
        title: 'Putting it all together',
        text: `A full 12-bar walking bassline mixes <strong>roots</strong>, <strong>chord tones</strong>, <strong>scale notes</strong> and <strong>chromatic approach</strong>. The form is: I I I I · IV IV I I · V IV I V. Bar 12 is a turnaround that pushes back to I.`,
        audio: [48, 52, 55, 57, 53, 57, 60, 53, 48, 52, 55, 57, 53, 57, 60, 53, 48, 52, 55, 57, 55, 50, 52, 48],
        references: [
          'Sweet Home Chicago',
          'Hoochie Coochie Man',
          "Stormy Monday Blues",
        ],
      },
      {
        type: 'exercise',
        title: 'Bars 1-4 (I chord)',
        description: 'Walking over the tonic for four bars.',
        notes: [48, 52, 55, 57, 48, 52, 55, 53, 48, 52, 55, 57, 48, 50, 52, 53],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bars 5-8 (IV → I)',
        description: 'Walk over IV for two bars then back to I.',
        notes: [53, 57, 60, 62, 53, 57, 60, 58, 48, 52, 55, 57, 48, 52, 55, 53],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bars 9-12 (V IV I V — turnaround)',
        description: 'V → IV → I → V turnaround.',
        notes: [55, 59, 62, 64, 53, 57, 60, 58, 48, 52, 55, 57, 55, 50, 52, 48],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-iivi',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking ii–V–I (Jazz)',
    summary: "The most-played bass progression in jazz. Master this and you'll fit in any session.",
    steps: [
      {
        type: 'theory',
        title: 'The core jazz cadence',
        text: `<strong>ii–V–I</strong> on its own is two bars (one bar of ii, one bar of V) followed by I. The bassist's job is to walk from the ii's root to the V's root to the I's root with smooth voice leading and (often) chromatic approach.`,
        audio: [50, 53, 57, 56, 55, 59, 62, 59, 60, 64, 67, 64],
        references: [
          'Autumn Leaves',
          'All The Things You Are',
          'A Night in Tunisia',
        ],
      },
      {
        type: 'exercise',
        title: 'Basic ii–V–I walk',
        description: 'Roots, scale tones, chromatic approach into each chord.',
        notes: [50, 53, 57, 56, 55, 59, 62, 59, 60, 64, 67, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With double-time fills',
        description: 'Double-time eighth-note fills heighten the groove.',
        notes: [50, 53, 55, 57, 56, 55, 53, 50, 55, 59, 62, 64, 65, 64, 62, 59, 60, 64, 67, 71, 72, 71, 67, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With substitutions',
        description: 'Chromatic substitution: ii → ♭II → I (tritone substitute).',
        notes: [50, 53, 57, 60, 61, 64, 67, 70, 60, 64, 67, 64],
        style: 'melody',
      },
    ],
  },
  // ================= READING =================
  {
    id: 'reading-rhythms',
    group: 'Reading',
    tag: 'Reading',
    title: 'Quarters, eighths and rests',
    summary: 'The smallest building blocks of rhythmic notation.',
    steps: [
      {
        type: 'theory',
        title: 'Pulses and subdivisions',
        text: `A <strong>quarter note</strong> takes one beat. An <strong>eighth note</strong> takes half a beat — two of them per beat. <strong>Rests</strong> are silent: a quarter rest is one silent beat, an eighth rest is half. Combining notes and rests is what gives rhythm its character.`,
      },
      {
        type: 'exercise',
        title: 'Steady quarters',
        description: 'Same note on every beat. Feel the steady pulse.',
        notes: [60, 60, 60, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Adding eighths',
        description: 'Same pulse, faster subdivisions. The eighth notes ride the beats.',
        notes: [60, 60, 62, 64, 60, 64, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixed rhythm melody',
        description: 'Quarters and eighths combined into a singable melodic phrase.',
        notes: [60, 64, 67, 64, 65, 67, 64, 60],
        style: 'melody',
      },
    ],
  },
  // ================= DUETS =================
  {
    id: 'duets',
    group: 'Duets',
    tag: 'Duets · Counterpoint',
    title: 'Two-voice basics',
    summary: 'Hear how two melodies move together. The simplest counterpoint patterns.',
    steps: [
      {
        type: 'theory',
        title: 'Two voices, two paths',
        text: `When two melodies play simultaneously, the interesting question is how they relate. <strong>Parallel motion</strong> moves both voices the same way; <strong>contrary motion</strong> sends them in opposite directions; <strong>oblique motion</strong> keeps one voice still while the other moves. Mixing all three is the heart of counterpoint.`,
      },
      {
        type: 'exercise',
        title: 'Parallel thirds',
        description: 'Both voices ascend the C major scale, always a third apart.',
        notes: [
          [60, 64], [62, 65], [64, 67], [65, 69], [67, 71], [69, 72], [71, 74], [72, 76],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Contrary motion',
        description: 'One voice goes up while the other goes down — they meet and cross.',
        notes: [
          [60, 84], [62, 81], [64, 79], [65, 77], [67, 76], [69, 74], [71, 72], [72, 71],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Call &amp; response',
        description: 'Two voices trade short melodic phrases — one calls, the other answers.',
        notes: [
          [60, 60], [62, 60], [64, 60], [65, 60],
          [60, 65], [60, 64], [60, 62], [60, 60],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Upper voice on its own',
        description: 'Just the top line of the parallel-thirds duet — useful to internalise before adding the second voice.',
        notes: [64, 65, 67, 69, 71, 72, 74, 76],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lower voice on its own',
        description: 'Same exercise from the bottom voice\'s perspective.',
        notes: [60, 62, 64, 65, 67, 69, 71, 72],
        style: 'melody',
      },
    ],
  },
  // ============== FINAL CHALLENGE ==============
  {
    id: 'challenge-mixed',
    group: 'Challenges',
    tag: 'Challenge · Final',
    title: 'Final challenge',
    summary: 'Everything together: scale colour, voicing, rhythm and a hint of bass.',
    steps: [
      {
        type: 'exercise',
        title: 'Scale + arpeggio',
        description: 'A scale fragment that resolves into an arpeggio.',
        notes: [60, 62, 64, 65, 67, 64, 67, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Chord change with passing notes',
        description: 'C → Am → F → G outlined with a melodic line.',
        notes: [60, 64, 65, 64, 69, 72, 69, 65, 60, 65, 65, 67, 67, 71, 72, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bass + chord finale',
        description: 'A short walking bass against a chord — your final piece.',
        notes: [
          [48, 60, 64, 67],
          [50, 60, 64, 67],
          [52, 60, 64, 67],
          [55, 60, 64, 67],
        ],
        style: 'progression',
      },
    ],
  },
];

export const GROUPS = ['Scales', 'Challenges', 'Chords', 'Progressions', 'Walking Bass', 'Reading', 'Duets'];
