// Curriculum data — modules grouped, each with multiple steps.
// Step types: 'theory' (text only) or 'exercise' (sheet + audio).

export const MODULES = [
  // ================= SCALES =================
  {
    id: 'major-scale',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'The Major Scale',
    summary: 'Build, hear and recognise the major scale family.',
    steps: [
      {
        type: 'theory',
        title: 'Pattern of whole and half steps',
        text: `The major scale is built from a fixed pattern of intervals: <strong>W-W-H-W-W-W-H</strong> (W = whole step / 2 semitones, H = half step / 1 semitone). Starting from C, every white key in order gives you C major: C D E F G A B C. The half steps fall between E–F and B–C. This pattern is what makes the scale sound bright and "resolved".`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '3', '4', '5', '6', '7', '8'],
          steps: ['W', 'W', 'H', 'W', 'W', 'W', 'H'],
        },
        audio: [60, 62, 64, 65, 67, 69, 71, 72],
        references: [
          'Twinkle Twinkle Little Star — pure C major',
          'Let It Be (The Beatles) — built on a major key',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Hear the C major scale ascending, one note per beat.',
        notes: [60, 62, 64, 65, 67, 69, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'The same scale played in reverse — feel how it resolves coming back to the tonic.',
        notes: [72, 71, 69, 67, 65, 64, 62, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With rests',
        description: 'Same scale, but every second beat is silent. Notice how the rest reshapes a familiar line.',
        notes: [60, null, 62, null, 64, null, 65, null, 67, null, 69, null, 71, null, 72, null],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Singable melody',
        description: 'A short, catchy melody using only major scale notes — the kind of phrase that sticks in your head.',
        notes: [60, 62, 64, 67, 64, 65, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Broken thirds',
        description: 'A classic scale study: every scale degree is followed by the note a third above it (1-3, 2-4, 3-5, …) — pairs of eighth notes the whole way up.',
        notes: [
          { m: 60, t: 'e' }, { m: 64, t: 'e' }, { m: 62, t: 'e' }, { m: 65, t: 'e' },
          { m: 64, t: 'e' }, { m: 67, t: 'e' }, { m: 65, t: 'e' }, { m: 69, t: 'e' },
          { m: 67, t: 'e' }, { m: 71, t: 'e' }, { m: 69, t: 'e' }, { m: 72, t: 'e' },
          { m: 71, t: 'e' }, { m: 74, t: 'e' }, { m: 72, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-2, 2-3, 3-4 …)',
        description: 'Method-book staple: climb the scale in overlapping pairs of adjacent notes (1-2, 2-3, 3-4, …). Eighth notes the whole way, finishing on the tonic.',
        notes: [
          { m: 60, t: 'e' }, { m: 62, t: 'e' }, { m: 62, t: 'e' }, { m: 64, t: 'e' },
          { m: 64, t: 'e' }, { m: 65, t: 'e' }, { m: 65, t: 'e' }, { m: 67, t: 'e' },
          { m: 67, t: 'e' }, { m: 69, t: 'e' }, { m: 69, t: 'e' }, { m: 71, t: 'e' },
          { m: 71, t: 'e' }, { m: 72, t: 'e' }, 72,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-7, 7-6, 6-5 …)',
        description: 'The same pattern coming down — overlapping pairs of adjacent notes from the top of the scale back to the tonic.',
        notes: [
          { m: 72, t: 'e' }, { m: 71, t: 'e' }, { m: 71, t: 'e' }, { m: 69, t: 'e' },
          { m: 69, t: 'e' }, { m: 67, t: 'e' }, { m: 67, t: 'e' }, { m: 65, t: 'e' },
          { m: 65, t: 'e' }, { m: 64, t: 'e' }, { m: 64, t: 'e' }, { m: 62, t: 'e' },
          { m: 62, t: 'e' }, { m: 60, t: 'e' }, 60,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-2-3, 2-3-4 …)',
        description: 'Overlapping three-note groups — a classic method-book pattern. Each group fits in one beat as triplet eighths.',
        notes: [
          { m: 60, t: 'et' }, { m: 62, t: 'et' }, { m: 64, t: 'et' },
          { m: 62, t: 'et' }, { m: 64, t: 'et' }, { m: 65, t: 'et' },
          { m: 64, t: 'et' }, { m: 65, t: 'et' }, { m: 67, t: 'et' },
          { m: 65, t: 'et' }, { m: 67, t: 'et' }, { m: 69, t: 'et' },
          { m: 67, t: 'et' }, { m: 69, t: 'et' }, { m: 71, t: 'et' },
          { m: 69, t: 'et' }, { m: 71, t: 'et' }, { m: 72, t: 'et' },
          { m: 72, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-7-6, 7-6-5 …)',
        description: 'Same three-note grouping pattern, this time descending from the upper tonic.',
        notes: [
          { m: 72, t: 'et' }, { m: 71, t: 'et' }, { m: 69, t: 'et' },
          { m: 71, t: 'et' }, { m: 69, t: 'et' }, { m: 67, t: 'et' },
          { m: 69, t: 'et' }, { m: 67, t: 'et' }, { m: 65, t: 'et' },
          { m: 67, t: 'et' }, { m: 65, t: 'et' }, { m: 64, t: 'et' },
          { m: 65, t: 'et' }, { m: 64, t: 'et' }, { m: 62, t: 'et' },
          { m: 64, t: 'et' }, { m: 62, t: 'et' }, { m: 60, t: 'et' },
          { m: 60, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'natural-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Natural Minor Scale',
    summary: 'The minor counterpart of major. Same notes as A minor played from A.',
    steps: [
      {
        type: 'theory',
        title: 'A minor and the relative key',
        text: `Natural minor uses the same notes as the major scale starting on the 6th degree. C major shares notes with A natural minor: A B C D E F G A. Its interval pattern is <strong>W-H-W-W-H-W-W</strong> — the half steps now fall between B–C and E–F. The lowered 3rd, 6th and 7th compared to major give it that darker, contemplative colour.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '♭3', '4', '5', '♭6', '♭7', '8'],
          steps: ['W', 'H', 'W', 'W', 'H', 'W', 'W'],
        },
        audio: [69, 71, 72, 74, 76, 77, 79, 81],
        references: [
          'Stairway to Heaven (Led Zeppelin) — A minor',
          'Hotel California (Eagles) — uses natural minor freely',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending in A',
        description: 'Climb A natural minor.',
        notes: [69, 71, 72, 74, 76, 77, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending in A',
        description: 'Same scale coming back down. Listen to the lowered 7th (G) instead of G♯.',
        notes: [81, 79, 77, 76, 74, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Sad melody',
        description: 'Short melodic phrase that uses the lowered 6th and 7th — that natural-minor wistful feel.',
        notes: [69, 72, 71, 69, 67, 65, 67, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Climbing line',
        description: 'A line that lifts the ear up through the scale, leaning back to the previous note before each new climb.',
        notes: [69, 71, 72, 71, 74, 76, 74, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-2, 2-3 …)',
        description: 'Overlapping pairs of adjacent notes climbing A natural minor — the lowered 3rd, 6th and 7th are all easy to feel in this pattern.',
        notes: [
          { m: 69, t: 'e' }, { m: 71, t: 'e' }, { m: 71, t: 'e' }, { m: 72, t: 'e' },
          { m: 72, t: 'e' }, { m: 74, t: 'e' }, { m: 74, t: 'e' }, { m: 76, t: 'e' },
          { m: 76, t: 'e' }, { m: 77, t: 'e' }, { m: 77, t: 'e' }, { m: 79, t: 'e' },
          { m: 79, t: 'e' }, { m: 81, t: 'e' }, 81,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-7, 7-6 …)',
        description: 'Same overlapping-pair shape coming back down through A natural minor.',
        notes: [
          { m: 81, t: 'e' }, { m: 79, t: 'e' }, { m: 79, t: 'e' }, { m: 77, t: 'e' },
          { m: 77, t: 'e' }, { m: 76, t: 'e' }, { m: 76, t: 'e' }, { m: 74, t: 'e' },
          { m: 74, t: 'e' }, { m: 72, t: 'e' }, { m: 72, t: 'e' }, { m: 71, t: 'e' },
          { m: 71, t: 'e' }, { m: 69, t: 'e' }, 69,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-2-3, 2-3-4 …)',
        description: 'Overlapping three-note groups in A minor — triplet eighths, one group per beat.',
        notes: [
          { m: 69, t: 'et' }, { m: 71, t: 'et' }, { m: 72, t: 'et' },
          { m: 71, t: 'et' }, { m: 72, t: 'et' }, { m: 74, t: 'et' },
          { m: 72, t: 'et' }, { m: 74, t: 'et' }, { m: 76, t: 'et' },
          { m: 74, t: 'et' }, { m: 76, t: 'et' }, { m: 77, t: 'et' },
          { m: 76, t: 'et' }, { m: 77, t: 'et' }, { m: 79, t: 'et' },
          { m: 77, t: 'et' }, { m: 79, t: 'et' }, { m: 81, t: 'et' },
          { m: 81, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-7-6, 7-6-5 …)',
        description: 'Three-note groups descending — a great way to internalise the ♭6 → 5 and ♭3 → 2 moves in A minor.',
        notes: [
          { m: 81, t: 'et' }, { m: 79, t: 'et' }, { m: 77, t: 'et' },
          { m: 79, t: 'et' }, { m: 77, t: 'et' }, { m: 76, t: 'et' },
          { m: 77, t: 'et' }, { m: 76, t: 'et' }, { m: 74, t: 'et' },
          { m: 76, t: 'et' }, { m: 74, t: 'et' }, { m: 72, t: 'et' },
          { m: 74, t: 'et' }, { m: 72, t: 'et' }, { m: 71, t: 'et' },
          { m: 72, t: 'et' }, { m: 71, t: 'et' }, { m: 69, t: 'et' },
          { m: 69, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'pentatonic-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Pentatonic Minor',
    summary: 'Five-note scale. The backbone of blues, rock and pop solos.',
    steps: [
      {
        type: 'theory',
        title: 'Why five notes?',
        text: `Pentatonic minor is natural minor with the 2nd and 6th degrees removed: <strong>1 ♭3 4 5 ♭7</strong>. Removing those half steps eliminates the most "dissonant" intervals — every note sounds good against the others, which is why solos built on the pentatonic rarely clash. In A: A C D E G.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '♭3', '4', '5', '♭7', '8'],
          steps: ['W+H', 'W', 'W', 'W+H', 'W'],
        },
        audio: [69, 72, 74, 76, 79, 81],
        references: [
          'Smoke on the Water (Deep Purple)',
          'Sunshine of Your Love (Cream)',
          "Most rock and blues guitar solos",
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'A minor pentatonic up.',
        notes: [69, 72, 74, 76, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'The same on the way back.',
        notes: [81, 79, 76, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bluesy lick',
        description: 'Pentatonic minor used in a typical lick — eighth-note pickup with a held resolution on the root.',
        notes: [{ m: 76, t: 'e' }, { m: 79, t: 'e' }, 81, 79, { m: 76, t: 'e' }, { m: 74, t: 'e' }, 72, { m: 69, t: 'h' }],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Solo phrase',
        description: 'A longer melodic phrase a guitarist or vocalist might improvise over a minor groove.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72, 76, 79, 81, 79],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-2, 2-3 …)',
        description: 'Overlapping pairs of adjacent pentatonic notes — each interval is a minor third or a whole step, never a half step. Great for warm-ups.',
        notes: [
          { m: 69, t: 'e' }, { m: 72, t: 'e' }, { m: 72, t: 'e' }, { m: 74, t: 'e' },
          { m: 74, t: 'e' }, { m: 76, t: 'e' }, { m: 76, t: 'e' }, { m: 79, t: 'e' },
          { m: 79, t: 'e' }, { m: 81, t: 'e' }, 81,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-7, 7-6 …)',
        description: 'Overlapping descending pairs — typical opening to a blues turn of phrase.',
        notes: [
          { m: 81, t: 'e' }, { m: 79, t: 'e' }, { m: 79, t: 'e' }, { m: 76, t: 'e' },
          { m: 76, t: 'e' }, { m: 74, t: 'e' }, { m: 74, t: 'e' }, { m: 72, t: 'e' },
          { m: 72, t: 'e' }, { m: 69, t: 'e' }, 69,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-2-3, 2-3-4 …)',
        description: 'Three-note groups climbing the pentatonic — useful for guitarists practising position playing.',
        notes: [
          { m: 69, t: 'et' }, { m: 72, t: 'et' }, { m: 74, t: 'et' },
          { m: 72, t: 'et' }, { m: 74, t: 'et' }, { m: 76, t: 'et' },
          { m: 74, t: 'et' }, { m: 76, t: 'et' }, { m: 79, t: 'et' },
          { m: 76, t: 'et' }, { m: 79, t: 'et' }, { m: 81, t: 'et' },
          { m: 81, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-7-6, 7-6-5 …)',
        description: 'The descending three-note groups — sounds like a classic rock lick on its own.',
        notes: [
          { m: 81, t: 'et' }, { m: 79, t: 'et' }, { m: 76, t: 'et' },
          { m: 79, t: 'et' }, { m: 76, t: 'et' }, { m: 74, t: 'et' },
          { m: 76, t: 'et' }, { m: 74, t: 'et' }, { m: 72, t: 'et' },
          { m: 74, t: 'et' }, { m: 72, t: 'et' }, { m: 69, t: 'et' },
          { m: 69, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'pentatonic-major',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Pentatonic Major',
    summary: 'Major\'s five-note cousin. The bedrock of country, gospel and Brazilian folk.',
    steps: [
      {
        type: 'theory',
        title: 'Drop the half steps',
        text: `Major pentatonic removes the 4th and 7th from the major scale: <strong>1 2 3 5 6</strong>. No half steps means almost every combination sounds consonant — perfect for vocal melodies and singalongs. In C: C D E G A.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '3', '5', '6', '8'],
          steps: ['W', 'W', 'W+H', 'W', 'W+H'],
        },
        audio: [60, 62, 64, 67, 69, 72],
        references: [
          'Amazing Grace — pentatonic major',
          'My Girl (The Temptations)',
          'Brazilian sambas often pivot on it',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Climb C major pentatonic.',
        notes: [60, 62, 64, 67, 69, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'And down again.',
        notes: [72, 69, 67, 64, 62, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Country lick',
        description: 'A typical country/folk phrase with eighth-note grace notes and a long final root.',
        notes: [60, { m: 64, t: 'e' }, { m: 67, t: 'e' }, 69, { m: 67, t: 'e' }, { m: 64, t: 'e' }, 62, { m: 60, t: 'h' }],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Brazilian-flavoured phrase',
        description: 'A laid-back melody — characteristic of Brazilian popular music.',
        notes: [62, 64, 67, 69, 64, 67, 69, 72, 69, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-2, 2-3 …)',
        description: 'Overlapping pairs of adjacent pentatonic notes climbing C major pentatonic.',
        notes: [
          { m: 60, t: 'e' }, { m: 62, t: 'e' }, { m: 62, t: 'e' }, { m: 64, t: 'e' },
          { m: 64, t: 'e' }, { m: 67, t: 'e' }, { m: 67, t: 'e' }, { m: 69, t: 'e' },
          { m: 69, t: 'e' }, { m: 72, t: 'e' }, 72,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-7, 7-6 …)',
        description: 'The same overlapping-pair pattern coming back down.',
        notes: [
          { m: 72, t: 'e' }, { m: 69, t: 'e' }, { m: 69, t: 'e' }, { m: 67, t: 'e' },
          { m: 67, t: 'e' }, { m: 64, t: 'e' }, { m: 64, t: 'e' }, { m: 62, t: 'e' },
          { m: 62, t: 'e' }, { m: 60, t: 'e' }, 60,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-2-3, 2-3-4 …)',
        description: 'Three-note groups climbing the C major pentatonic — a foundational pattern in country and gospel licks.',
        notes: [
          { m: 60, t: 'et' }, { m: 62, t: 'et' }, { m: 64, t: 'et' },
          { m: 62, t: 'et' }, { m: 64, t: 'et' }, { m: 67, t: 'et' },
          { m: 64, t: 'et' }, { m: 67, t: 'et' }, { m: 69, t: 'et' },
          { m: 67, t: 'et' }, { m: 69, t: 'et' }, { m: 72, t: 'et' },
          { m: 72, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-7-6, 7-6-5 …)',
        description: 'Descending three-note groups — typical of folk and Brazilian melodic ornaments.',
        notes: [
          { m: 72, t: 'et' }, { m: 69, t: 'et' }, { m: 67, t: 'et' },
          { m: 69, t: 'et' }, { m: 67, t: 'et' }, { m: 64, t: 'et' },
          { m: 67, t: 'et' }, { m: 64, t: 'et' }, { m: 62, t: 'et' },
          { m: 64, t: 'et' }, { m: 62, t: 'et' }, { m: 60, t: 'et' },
          { m: 60, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'blues-scale',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Blues Scale',
    summary: 'Pentatonic minor plus a "blue note" — the soul of blues, jazz and rock.',
    steps: [
      {
        type: 'theory',
        title: 'The blue note',
        text: `The blues scale adds a chromatic note between the 4th and 5th of pentatonic minor — the famous <strong>♭5</strong> or "blue note": <strong>1 ♭3 4 ♭5 5 ♭7</strong>. That extra chromatic step gives the scale its iconic tension. In A: A C D E♭ E G.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '♭3', '4', '♭5', '5', '♭7', '8'],
          steps: ['W+H', 'W', 'H', 'H', 'W+H', 'W'],
        },
        audio: [69, 72, 74, 75, 76, 79, 81],
        references: [
          'Sweet Home Chicago (Robert Johnson)',
          "Pride and Joy (Stevie Ray Vaughan)",
          'Almost any 12-bar blues solo',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending',
        description: 'Hear that blue note slide between the 4th and 5th.',
        notes: [69, 72, 74, 75, 76, 79, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending',
        description: 'Down through the blue note again.',
        notes: [81, 79, 76, 75, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Classic blues lick',
        description: 'A signature lick that lands on the blue note before resolving.',
        notes: [76, 79, 81, 79, 76, 75, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Call & response phrase',
        description: 'A two-part melodic statement — the call goes up, the response answers down.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72, 75, 74, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-♭3, ♭3-4 …)',
        description: 'Overlapping pairs through the blues scale — the half-step approach to the 5 (♭5 → 5) lands inside the run, drilling the blue note in context.',
        notes: [
          { m: 69, t: 'e' }, { m: 72, t: 'e' }, { m: 72, t: 'e' }, { m: 74, t: 'e' },
          { m: 74, t: 'e' }, { m: 75, t: 'e' }, { m: 75, t: 'e' }, { m: 76, t: 'e' },
          { m: 76, t: 'e' }, { m: 79, t: 'e' }, { m: 79, t: 'e' }, { m: 81, t: 'e' },
          { m: 81, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-♭7, ♭7-5 …)',
        description: 'Descending overlapping pairs — the 5 → ♭5 move on the way down is a classic blues turn.',
        notes: [
          { m: 81, t: 'e' }, { m: 79, t: 'e' }, { m: 79, t: 'e' }, { m: 76, t: 'e' },
          { m: 76, t: 'e' }, { m: 75, t: 'e' }, { m: 75, t: 'e' }, { m: 74, t: 'e' },
          { m: 74, t: 'e' }, { m: 72, t: 'e' }, { m: 72, t: 'e' }, { m: 69, t: 'e' },
          { m: 69, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-♭3-4, ♭3-4-♭5 …)',
        description: 'Three-note groups climbing the blues scale — every other group includes the blue note (♭5), so the tension is constantly recycled.',
        notes: [
          { m: 69, t: 'et' }, { m: 72, t: 'et' }, { m: 74, t: 'et' },
          { m: 72, t: 'et' }, { m: 74, t: 'et' }, { m: 75, t: 'et' },
          { m: 74, t: 'et' }, { m: 75, t: 'et' }, { m: 76, t: 'et' },
          { m: 75, t: 'et' }, { m: 76, t: 'et' }, { m: 79, t: 'et' },
          { m: 76, t: 'et' }, { m: 79, t: 'et' }, { m: 81, t: 'et' },
          { m: 81, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-♭7-5, ♭7-5-♭5 …)',
        description: 'Three-note groups coming back down — pulls the blue note through every transition.',
        notes: [
          { m: 81, t: 'et' }, { m: 79, t: 'et' }, { m: 76, t: 'et' },
          { m: 79, t: 'et' }, { m: 76, t: 'et' }, { m: 75, t: 'et' },
          { m: 76, t: 'et' }, { m: 75, t: 'et' }, { m: 74, t: 'et' },
          { m: 75, t: 'et' }, { m: 74, t: 'et' }, { m: 72, t: 'et' },
          { m: 74, t: 'et' }, { m: 72, t: 'et' }, { m: 69, t: 'et' },
          { m: 69, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'harmonic-minor',
    group: 'Scales',
    tag: 'Theory · Scales',
    title: 'Harmonic Minor',
    summary: 'Natural minor with a raised 7th. Exotic, dramatic — the heart of flamenco and metal.',
    steps: [
      {
        type: 'theory',
        title: 'Raise the leading tone',
        text: `Harmonic minor takes natural minor and lifts the 7th degree by a half step: <strong>1 2 ♭3 4 5 ♭6 7</strong>. The big augmented-second leap between ♭6 and 7 gives the scale its dramatic, slightly Middle-Eastern flavour, and the raised 7 functions as a leading tone — the reason it was invented for harmony in the first place.`,
        diagram: {
          type: 'intervals',
          labels: ['1', '2', '♭3', '4', '5', '♭6', '7', '8'],
          steps: ['W', 'H', 'W', 'W', 'H', 'W+H', 'H'],
        },
        audio: [69, 71, 72, 74, 76, 77, 80, 81],
        references: [
          'Flamenco music — its native idiom',
          'Hava Nagila (traditional)',
          'Yngwie Malmsteen — neoclassical metal solos',
        ],
      },
      {
        type: 'exercise',
        title: 'Ascending in A',
        description: 'Watch out for the augmented 2nd between the 6th and 7th — it sounds exotic.',
        notes: [69, 71, 72, 74, 76, 77, 80, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending in A',
        description: 'Coming back through that big leap.',
        notes: [81, 80, 77, 76, 74, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Flamenco-style phrase',
        description: 'A dramatic melodic phrase that evokes Spanish music.',
        notes: [69, 72, 76, 77, 80, 77, 76, 72, 71, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Classical mini-phrase',
        description: 'The leading tone resolves up to the tonic — the foundation of harmonic-minor harmony.',
        notes: [76, 77, 80, 81, 80, 77, 76, 72, 69, 80, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs ascending (1-2, 2-♭3 …)',
        description: 'Overlapping pairs climbing harmonic minor. The augmented 2nd between ♭6 and 7 (F → G#) sits squarely inside one pair — drill it until it sounds normal.',
        notes: [
          { m: 69, t: 'e' }, { m: 71, t: 'e' }, { m: 71, t: 'e' }, { m: 72, t: 'e' },
          { m: 72, t: 'e' }, { m: 74, t: 'e' }, { m: 74, t: 'e' }, { m: 76, t: 'e' },
          { m: 76, t: 'e' }, { m: 77, t: 'e' }, { m: 77, t: 'e' }, { m: 80, t: 'e' },
          { m: 80, t: 'e' }, { m: 81, t: 'e' }, 81,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pairs descending (8-7, 7-♭6 …)',
        description: 'Descending pairs — the 7 → ♭6 jump (G# → F) is the same augmented 2nd, just landing on the way down.',
        notes: [
          { m: 81, t: 'e' }, { m: 80, t: 'e' }, { m: 80, t: 'e' }, { m: 77, t: 'e' },
          { m: 77, t: 'e' }, { m: 76, t: 'e' }, { m: 76, t: 'e' }, { m: 74, t: 'e' },
          { m: 74, t: 'e' }, { m: 72, t: 'e' }, { m: 72, t: 'e' }, { m: 71, t: 'e' },
          { m: 71, t: 'e' }, { m: 69, t: 'e' }, 69,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes ascending (1-2-♭3, 2-♭3-4 …)',
        description: 'Three-note groups up. Group 5 (♭6-7-8) crosses the augmented 2nd as a triplet — the most demanding fingering in the scale.',
        notes: [
          { m: 69, t: 'et' }, { m: 71, t: 'et' }, { m: 72, t: 'et' },
          { m: 71, t: 'et' }, { m: 72, t: 'et' }, { m: 74, t: 'et' },
          { m: 72, t: 'et' }, { m: 74, t: 'et' }, { m: 76, t: 'et' },
          { m: 74, t: 'et' }, { m: 76, t: 'et' }, { m: 77, t: 'et' },
          { m: 76, t: 'et' }, { m: 77, t: 'et' }, { m: 80, t: 'et' },
          { m: 77, t: 'et' }, { m: 80, t: 'et' }, { m: 81, t: 'et' },
          { m: 81, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Threes descending (8-7-♭6, 7-♭6-5 …)',
        description: 'Descending three-note groups — the augmented 2nd appears in the first two triads (8-7-♭6 and 7-♭6-5).',
        notes: [
          { m: 81, t: 'et' }, { m: 80, t: 'et' }, { m: 77, t: 'et' },
          { m: 80, t: 'et' }, { m: 77, t: 'et' }, { m: 76, t: 'et' },
          { m: 77, t: 'et' }, { m: 76, t: 'et' }, { m: 74, t: 'et' },
          { m: 76, t: 'et' }, { m: 74, t: 'et' }, { m: 72, t: 'et' },
          { m: 74, t: 'et' }, { m: 72, t: 'et' }, { m: 71, t: 'et' },
          { m: 72, t: 'et' }, { m: 71, t: 'et' }, { m: 69, t: 'et' },
          { m: 69, t: 'h' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'greek-modes',
    group: 'Scales',
    tag: 'Theory · Modes',
    title: 'Greek Modes',
    summary: 'Seven modes, one parent scale. Each one has its own colour.',
    steps: [
      {
        type: 'theory',
        title: 'Modes are starting points',
        text: `The seven Greek modes are obtained by playing the major scale starting from each of its degrees. Same notes, different tonic — and therefore a different feel. Ionian (1) is plain major; Aeolian (6) is natural minor. The four below are the most expressive non-diatonic colours.`,
      },
      {
        type: 'exercise',
        title: 'Dorian (D from C major)',
        description: 'Minor with a raised 6th. Jazzy and slightly hopeful.',
        notes: [62, 64, 65, 67, 69, 71, 72, 74],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Phrygian (E from C major)',
        description: 'Minor with a flat 2nd. Dark, Spanish/Middle-Eastern colour.',
        notes: [64, 65, 67, 69, 71, 72, 74, 76],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lydian (F from C major)',
        description: 'Major with a raised 4th. Floating, dreamy quality.',
        notes: [65, 67, 69, 71, 72, 74, 76, 77],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixolydian (G from C major)',
        description: 'Major with a flat 7th. Dominant, bluesy.',
        notes: [67, 69, 71, 72, 74, 76, 77, 79],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Dorian melody',
        description: 'A tune that leans on B — the raised 6th that distinguishes D Dorian from D natural minor.',
        notes: [62, 65, 67, 71, 69, 71, 67, 65, 64, 62],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lydian melody',
        description: 'Phrase that leans on the raised 4th — Lydian\'s signature dreamy lift.',
        notes: [65, 67, 71, 72, 71, 67, 71, 65],
        style: 'melody',
      },
    ],
  },
  // ================= CHORDS =================
  {
    id: 'major-triad',
    group: 'Chords',
    tag: 'Theory · Chords',
    title: 'Major Triad & Inversions',
    summary: 'Root, 3rd, 5th — and the same chord stacked three different ways.',
    steps: [
      {
        type: 'theory',
        title: 'The three positions',
        text: `A triad is three notes: root, 3rd, 5th. Reorder them and you get the same chord with a different bottom note. <strong>Root position</strong>: 1-3-5. <strong>1st inversion</strong>: 3-5-1. <strong>2nd inversion</strong>: 5-1-3. The chord is still C major in all three — but the bass shifts the colour and the voice-leading possibilities.`,
      },
      {
        type: 'exercise',
        title: 'Root position — C E G',
        description: 'Bottom-up stacking: the root is in the bass.',
        notes: [60, 64, 67],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '1st inversion — E G C',
        description: 'Same chord with the 3rd in the bass. Sounds slightly less stable, often used as a passing voicing.',
        notes: [64, 67, 72],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '2nd inversion — G C E',
        description: '5th in the bass. Common as a cadential 6/4 chord before resolving.',
        notes: [67, 72, 76],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Triad melody',
        description: 'A bouncing melodic line that lives entirely on the C major triad notes.',
        notes: [60, 64, 67, 64, 60, 67, 72, 67],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Triad with passing tones',
        description: 'Triad notes connected by the scale steps in between. Common building block of melodies.',
        notes: [60, 62, 64, 65, 67, 65, 64, 60],
        style: 'melody',
      },
    ],
  },
  {
    id: 'minor-triad',
    group: 'Chords',
    tag: 'Theory · Chords',
    title: 'Minor Triad & Inversions',
    summary: 'Same idea, flatter 3rd. Darker mood.',
    steps: [
      {
        type: 'theory',
        title: 'Flatten the 3rd',
        text: `A minor triad lowers the major's 3rd by a semitone: <strong>1 ♭3 5</strong>. In A minor: A C E. The same three inversions (root / 1st / 2nd) apply. Stacking and rearranging unlocks rich voice-leading without changing the chord's identity.`,
      },
      {
        type: 'exercise',
        title: 'Root position — A C E',
        description: 'The "anchor" voicing.',
        notes: [69, 72, 76],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '1st inversion — C E A',
        description: '3rd in the bass.',
        notes: [72, 76, 81],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: '2nd inversion — E A C',
        description: '5th in the bass.',
        notes: [76, 81, 84],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Minor triad melody',
        description: 'A melodic phrase that outlines the A minor triad — moody, contemplative.',
        notes: [69, 72, 76, 72, 69, 76, 72, 69],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Triad with neighbours',
        description: 'Triad notes ornamented with quick chromatic neighbour tones — the neighbours play as eighths so they decorate, not interrupt.',
        notes: [72, { m: 71, t: 'e' }, { m: 72, t: 'e' }, 76, { m: 75, t: 'e' }, { m: 76, t: 'e' }, 81, 76],
        style: 'melody',
      },
    ],
  },
  {
    id: 'tetrads',
    group: 'Chords',
    tag: 'Theory · Tetrads',
    title: 'Tetrads (7th chords)',
    summary: 'Add a fourth note on top of the triad — the doorway into jazz harmony.',
    steps: [
      {
        type: 'theory',
        title: 'Adding the 7th',
        text: `A <strong>tetrad</strong> stacks four notes a third apart: 1-3-5-7. The 7th gives the chord new colours: <strong>major 7</strong> (raised 7) is dreamy and bright; <strong>dominant 7</strong> (♭7) wants to resolve and is the workhorse of blues and jazz; <strong>minor 7</strong> (♭3, ♭7) is soulful. Most jazz lead sheets are written in 7th chords.`,
      },
      {
        type: 'exercise',
        title: 'C major 7 chord',
        description: 'C - E - G - B. The major 7th sits a half-step below the octave.',
        notes: [60, 64, 67, 71],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'C dominant 7',
        description: 'Lower the 7th by a semitone (C - E - G - B♭). Bluesy, restless — typically resolves down a fifth.',
        notes: [60, 64, 67, 70],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'C minor 7',
        description: 'C - E♭ - G - B♭. Smooth, soulful colour — the harmonic backbone of countless ballads.',
        notes: [60, 63, 67, 70],
        style: 'chord',
      },
      {
        type: 'exercise',
        title: 'Cmaj7 arpeggio melody',
        description: 'A melodic line that climbs the major 7 arpeggio to the octave, then settles back on the root.',
        notes: [60, 64, 67, 71, 72, 71, 67, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bebop-flavoured 7th line',
        description: 'Eighth-note line that traces a G7 arpeggio, slips down a half-step (F→E) and lands on the 3rd of Cmaj7.',
        notes: [
          { m: 55, t: 'e' }, { m: 59, t: 'e' }, { m: 62, t: 'e' }, { m: 65, t: 'e' },
          { m: 64, t: 'e' }, { m: 60, t: 'e' }, { m: 64, t: 'e' }, { m: 67, t: 'e' },
          { m: 71, t: 'h' }, { m: 67, t: 'h' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'ii–V–I in 7ths',
        description: 'The iconic jazz cadence with seventh chords: Dm7 → G7 → Cmaj7. The harmonic engine of bebop.',
        notes: [
          [62, 65, 69, 72],
          [55, 59, 62, 65],
          [60, 64, 67, 71],
        ],
        style: 'progression',
      },
    ],
  },
  {
    id: 'arpeggios',
    group: 'Chords',
    tag: 'Theory · Arpeggios',
    title: 'Arpeggios',
    summary: 'A chord, but one note at a time. Bridge between chords and melody.',
    steps: [
      {
        type: 'theory',
        title: 'What is an arpeggio?',
        text: `Take any chord and play its notes one after another instead of together — that's an arpeggio. They're how melodies "imply" the harmony underneath. Singers use them to outline chord changes; bass lines walk through them.`,
      },
      {
        type: 'exercise',
        title: 'C major arpeggio (1-3-5-8)',
        description: 'Outline the major triad note-by-note up to the octave.',
        notes: [60, 64, 67, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'A minor arpeggio',
        description: 'Same shape, minor flavour.',
        notes: [69, 72, 76, 81],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'C major 7 arpeggio',
        description: 'Add the major 7th (B) for a jazzy colour.',
        notes: [60, 64, 67, 71, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Arpeggio melody',
        description: 'A melodic line built almost entirely on arpeggio notes — outlines the harmony without ever stating a chord.',
        notes: [60, 64, 67, 64, 67, 72, 67, 64, 60],
        style: 'melody',
      },
    ],
  },
  // ================= HARMONY: PROGRESSIONS =================
  {
    id: 'prog-i-v-vi-iv',
    group: 'Progressions',
    tag: 'Progressions · Pop',
    title: 'I–V–vi–IV (Pop axis)',
    summary: 'The most popular progression in modern pop. Instantly familiar.',
    steps: [
      {
        type: 'theory',
        title: 'The "axis of awesome"',
        text: `Each chord drops or lifts the harmonic tension by exactly the right amount: <strong>I</strong> (home) → <strong>V</strong> (suspense) → <strong>vi</strong> (twist into minor) → <strong>IV</strong> (gentle return). In C major: C, G, Am, F.`,
        diagram: { type: 'progression', chords: ['I', 'V', 'vi', 'IV'] },
        audio: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [65, 69, 72]],
        audioStyle: 'progression',
        references: [
          "Let It Be (The Beatles)",
          "Don't Stop Believin' (Journey)",
          'Someone Like You (Adele)',
          'With or Without You (U2)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        description: 'Play and feel each chord land.',
        notes: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [65, 69, 72]],
        chordSymbols: ['C', 'G', 'Am', 'F'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody outlining the chords',
        description: 'A simple pop melody that lands on a chord tone over each new chord.',
        notes: [60, 64, 67, 71, 67, 71, 74, 71, 69, 72, 76, 72, 65, 69, 72, 69],
        chordSymbols: ['C', 'G', 'Am', 'F'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Riff that adapts per chord',
        description: 'Four bars of a recurring rhythmic shape, each one re-aimed at the chord tones of the current chord.',
        notes: [64, 67, 64, 67, 71, 74, 71, 67, 69, 72, 69, 65, 65, 69, 72, 65],
        chordSymbols: ['C', 'G', 'Am', 'F'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-50s',
    group: 'Progressions',
    tag: 'Progressions · 50s',
    title: 'I–vi–IV–V (50s doo-wop)',
    summary: 'The "Stand by Me" loop. Defines an entire era of pop.',
    steps: [
      {
        type: 'theory',
        title: 'The doo-wop circle',
        text: `Take I, drop to vi, slide to IV, finish on V — and repeat. The vi keeps the major-key feel while adding a touch of melancholy; V then sets up the return to I. In C: C – Am – F – G.`,
        diagram: { type: 'progression', chords: ['I', 'vi', 'IV', 'V'] },
        audio: [[60, 64, 67], [69, 72, 76], [65, 69, 72], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Stand by Me (Ben E. King)',
          'Earth Angel (The Penguins)',
          "Heart and Soul (Hoagy Carmichael)",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        description: 'C – Am – F – G in slow motion.',
        notes: [[60, 64, 67], [69, 72, 76], [65, 69, 72], [67, 71, 74]],
        chordSymbols: ['C', 'Am', 'F', 'G'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody over the loop',
        description: 'A typical 50s vocal melody.',
        notes: [60, 64, 67, 64, 69, 72, 69, 64, 65, 69, 72, 69, 67, 71, 74, 71],
        chordSymbols: ['C', 'Am', 'F', 'G'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bass walk between chords',
        description: 'Bass line outlining each chord — root and 3rd or 5th — with a stepwise connector landing on the next root.',
        notes: [48, 52, 55, 57, 60, 57, 53, 55],
        chordSymbols: [['C', 'Am'], ['F', 'G']],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-12-bar-blues',
    group: 'Progressions',
    tag: 'Progressions · Blues',
    title: '12-bar Blues',
    summary: 'I, IV, V — the universal blueprint of blues, R&B, rock and jazz.',
    steps: [
      {
        type: 'theory',
        title: 'Twelve bars, three chords',
        text: `The blues form is twelve bars long: <strong>I I I I · IV IV I I · V IV I V</strong>. Three chords, infinite variations. With dominant-7 chords on every degree, you've got the foundation of blues, soul, jazz, country and rock & roll.`,
        diagram: { type: 'progression', chords: ['I7', 'IV7', 'I7', 'V7', 'IV7', 'I7'] },
        audio: [[60, 64, 67, 70], [65, 69, 72, 75], [60, 64, 67, 70], [67, 71, 74, 77], [65, 69, 72, 75], [60, 64, 67, 70]],
        audioStyle: 'progression',
        references: [
          'Sweet Home Chicago (Robert Johnson)',
          'Crossroads (Cream)',
          'Pride and Joy (Stevie Ray Vaughan)',
          'Boogie Woogie (any of the classics)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the basic 12-bar (condensed)',
        description: 'Six chords summarising the form.',
        notes: [
          [60, 64, 67, 70], [65, 69, 72, 75], [60, 64, 67, 70],
          [67, 71, 74, 77], [65, 69, 72, 75], [60, 64, 67, 70],
        ],
        chordSymbols: ['C7', 'F7', 'C7', 'G7', 'F7', 'C7'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Blues solo line',
        description: 'A classic 12-bar improvisation outline using the blues scale over each chord.',
        notes: [69, 72, 74, 75, 76, 79, 76, 75, 74, 72, 69, 67, 69, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking blues bassline',
        description: 'A walking bass over the condensed 6-bar shape (same as the chord exercise above): I, IV, I, V, IV, I.',
        notes: [48, 52, 55, 57, 53, 57, 60, 62, 48, 52, 55, 57, 55, 59, 62, 64, 53, 57, 60, 62, 48, 52, 55, 57],
        chordSymbols: ['C7', 'F7', 'C7', 'G7', 'F7', 'C7'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-ii-v-i',
    group: 'Progressions',
    tag: 'Progressions · Jazz',
    title: 'ii–V–I (Jazz cadence)',
    summary: "The most important progression in jazz. Resolves home in two perfect 5ths.",
    steps: [
      {
        type: 'theory',
        title: 'Two falling fifths',
        text: `<strong>ii–V–I</strong> creates the strongest harmonic resolution in tonal music: each chord root falls a perfect fifth into the next. With 7th chords (Dm7 → G7 → Cmaj7) you've got the central building block of jazz harmony.`,
        diagram: { type: 'progression', chords: ['ii7', 'V7', 'Imaj7'] },
        audio: [[62, 65, 69, 72], [55, 59, 62, 65], [60, 64, 67, 71]],
        audioStyle: 'progression',
        references: [
          'Autumn Leaves',
          'All The Things You Are',
          "Almost any jazz standard's last 4 bars",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear ii–V–I in 7ths',
        description: 'Dm7 → G7 → Cmaj7. Feel the falling 5ths in the bass.',
        notes: [[62, 65, 69, 72], [55, 59, 62, 65], [60, 64, 67, 71]],
        chordSymbols: ['Dm7', 'G7', 'Cmaj7'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Bebop melody',
        description: 'Eighth-note line: Dm7 arpeggio up, descending G7 line, then a clean Cmaj7 arpeggio. Three bars, one chord per bar.',
        notes: [
          { m: 62, t: 'e' }, { m: 65, t: 'e' }, { m: 69, t: 'e' }, { m: 72, t: 'e' }, { m: 71, t: 'e' }, { m: 69, t: 'e' }, { m: 65, t: 'e' }, { m: 62, t: 'e' },
          { m: 67, t: 'e' }, { m: 71, t: 'e' }, { m: 65, t: 'e' }, { m: 62, t: 'e' }, { m: 60, t: 'e' }, { m: 59, t: 'e' }, { m: 64, t: 'e' }, { m: 60, t: 'e' },
          { m: 60, t: 'e' }, { m: 64, t: 'e' }, { m: 67, t: 'e' }, { m: 71, t: 'e' }, { m: 72, t: 'h' },
        ],
        chordSymbols: ['Dm7', 'G7', 'Cmaj7'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Guide-tone line',
        description: 'Just the 3rd and 7th of each chord — sustained as half notes, the way a horn would actually voice the line.',
        notes: [
          { m: 65, t: 'h' }, { m: 72, t: 'h' },
          { m: 65, t: 'h' }, { m: 71, t: 'h' },
          { m: 64, t: 'h' }, { m: 71, t: 'h' },
        ],
        chordSymbols: ['Dm7', 'G7', 'Cmaj7'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-andalusian',
    group: 'Progressions',
    tag: 'Progressions · Spanish',
    title: 'Andalusian Cadence (i–VII–VI–V)',
    summary: 'A descending bass line in minor that defines flamenco and Spanish music.',
    steps: [
      {
        type: 'theory',
        title: 'The Phrygian descent',
        text: `Starting on minor i, the bass walks down in stepwise motion: <strong>i → VII → VI → V</strong>. The arrival on V (a major chord!) gives it that haunting Spanish/Phrygian flavour. In A minor: Am – G – F – E.`,
        diagram: { type: 'progression', chords: ['i', 'VII', 'VI', 'V'] },
        audio: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [52, 56, 59]],
        audioStyle: 'progression',
        references: [
          'Hit the Road Jack (Ray Charles)',
          'Sultans of Swing (Dire Straits) — coda',
          'Almost any flamenco piece',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the cadence',
        description: 'Am – G – F – E.',
        notes: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [52, 56, 59]],
        chordSymbols: ['Am', 'G', 'F', 'E'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Spanish-flavoured melody',
        description: 'Phrygian-flavoured melodic line over the descent.',
        notes: [69, 72, 76, 72, 67, 71, 65, 69, 64, 67, 65, 64],
        chordSymbols: ['Am', ['G', 'F'], 'E'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Descending bass line',
        description: 'Half notes — each chord root holds for two beats so the descent feels inevitable.',
        notes: [{ m: 57, t: 'h' }, { m: 55, t: 'h' }, { m: 53, t: 'h' }, { m: 52, t: 'h' }],
        chordSymbols: [['Am', 'G'], ['F', 'E']],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-pachelbel',
    group: 'Progressions',
    tag: 'Progressions · Classical',
    title: 'Pachelbel (I–V–vi–iii–IV–I–IV–V)',
    summary: "Canon in D. Eight chords that have powered hits from Bach to Coolio.",
    steps: [
      {
        type: 'theory',
        title: 'Eight chords, endless songs',
        text: `Pachelbel's Canon descends through almost every diatonic chord in the key, then climbs back to V. The descending bass line (D-A-B-F#-G-D-G-A in D major) is irresistibly catchy and has been reused in pop and rock for centuries.`,
        diagram: { type: 'progression', chords: ['I', 'V', 'vi', 'iii', 'IV', 'I', 'IV', 'V'] },
        audio: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [64, 67, 71], [65, 69, 72], [60, 64, 67], [65, 69, 72], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Canon in D (Pachelbel)',
          'Basket Case (Green Day)',
          'C U When U Get There (Coolio)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the canon progression',
        description: 'All 8 chords in C.',
        notes: [[60, 64, 67], [67, 71, 74], [69, 72, 76], [64, 67, 71], [65, 69, 72], [60, 64, 67], [65, 69, 72], [67, 71, 74]],
        chordSymbols: ['C', 'G', 'Am', 'Em', 'F', 'C', 'F', 'G'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Canon-style melody',
        description: "A simple counter-melody woven over the harmony.",
        notes: [72, 71, 69, 67, 65, 64, 65, 67, 65, 67, 65, 64, 65, 67, 71, 72],
        chordSymbols: [['C', 'G'], ['Am', 'Em'], ['F', 'C'], ['F', 'G']],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Pachelbel bass',
        description: 'The signature bass line — eight chord roots that sweep across the form: C G A E F C F G.',
        notes: [48, 55, 57, 52, 53, 48, 53, 55],
        chordSymbols: [['C', 'G', 'Am', 'Em'], ['F', 'C', 'F', 'G']],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-vi-iv-i-v',
    group: 'Progressions',
    tag: 'Progressions · Modern Pop',
    title: 'vi–IV–I–V (Sad pop)',
    summary: 'The "axis" rotated to start on the relative minor — modern emotional pop.',
    steps: [
      {
        type: 'theory',
        title: 'Same chords, different gravity',
        text: `Same four chords as I–V–vi–IV but starting on vi makes the listener hear the song in the relative minor at first, before the IV–I "turn around" lifts the mood. In C: Am – F – C – G.`,
        diagram: { type: 'progression', chords: ['vi', 'IV', 'I', 'V'] },
        audio: [[69, 72, 76], [65, 69, 72], [60, 64, 67], [67, 71, 74]],
        audioStyle: 'progression',
        references: [
          "Apologize (OneRepublic)",
          "Numb (Linkin Park)",
          "Save Yourself (Kaleo)",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the chords',
        notes: [[69, 72, 76], [65, 69, 72], [60, 64, 67], [67, 71, 74]],
        chordSymbols: ['Am', 'F', 'C', 'G'],
        style: 'progression',
        description: 'Am – F – C – G.',
      },
      {
        type: 'exercise',
        title: 'Singable topline',
        description: 'A melody that opens with a yearning minor and resolves up.',
        notes: [69, 72, 76, 72, 65, 69, 72, 69, 60, 64, 67, 64, 67, 71, 74, 71],
        chordSymbols: ['Am', 'F', 'C', 'G'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Counter-melody',
        description: 'A melodic counter-line that lifts from the minor into the IV resolution.',
        notes: [69, 72, 74, 76, 65, 67, 69, 72, 60, 62, 64, 67, 67, 71, 74, 76],
        chordSymbols: ['Am', 'F', 'C', 'G'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-minor-loop',
    group: 'Progressions',
    tag: 'Progressions · Minor',
    title: 'i–VII–VI–VII (Minor rock loop)',
    summary: 'Heavy, modal — the engine of countless rock and metal anthems.',
    steps: [
      {
        type: 'theory',
        title: 'Modal minor rock',
        text: `Stay in minor, treat the V as VII (a flat 7) — and you've got pure Aeolian rock. The progression has gravitas without ever using the leading tone, which keeps it grounded and earthy.`,
        diagram: { type: 'progression', chords: ['i', 'VII', 'VI', 'VII'] },
        audio: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [55, 59, 62]],
        audioStyle: 'progression',
        references: [
          'Stairway to Heaven (Led Zeppelin) — verse',
          'Mad World (Tears for Fears / Gary Jules)',
          'Numb (Linkin Park)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the loop',
        description: 'Am – G – F – G.',
        notes: [[57, 60, 64], [55, 59, 62], [53, 57, 60], [55, 59, 62]],
        chordSymbols: ['Am', 'G', 'F', 'G'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Riff over the loop',
        description: 'A pentatonic-minor riff that grooves over all four chords.',
        notes: [69, 72, 74, 76, 79, 76, 74, 72],
        chordSymbols: [['Am', 'G'], ['F', 'G']],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Melodic counter-line',
        description: 'A vocal-style line that rises and falls over the harmony.',
        notes: [69, 72, 76, 72, 71, 67, 65, 67, 65, 64, 67, 65],
        chordSymbols: ['Am', ['G', 'F'], 'G'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-royal-road',
    group: 'Progressions',
    tag: 'Progressions · J-Pop',
    title: 'Royal Road (IV–V–iii–vi)',
    summary: 'The sound of anime openings and modern J-pop.',
    steps: [
      {
        type: 'theory',
        title: 'Climb and resolve',
        text: `IV–V–iii–vi pushes upward (IV–V) then reflects (iii–vi) — like a question and a thoughtful answer. In Japanese pop it's so common it has its own name: "ouhouto", the Royal Road. In C: F – G – Em – Am.`,
        diagram: { type: 'progression', chords: ['IV', 'V', 'iii', 'vi'] },
        audio: [[65, 69, 72], [67, 71, 74], [64, 67, 71], [69, 72, 76]],
        audioStyle: 'progression',
        references: [
          'Cruel Angel\'s Thesis (Neon Genesis Evangelion)',
          'Pretender (Official Hige Dandism)',
          'Lemon (Kenshi Yonezu)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the loop',
        description: 'F – G – Em – Am.',
        notes: [[65, 69, 72], [67, 71, 74], [64, 67, 71], [69, 72, 76]],
        chordSymbols: ['F', 'G', 'Em', 'Am'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'J-pop topline',
        description: 'A bright, climbing vocal line.',
        notes: [65, 69, 72, 74, 67, 71, 74, 76, 67, 71, 74, 71, 69, 72, 76, 72],
        chordSymbols: ['F', 'G', 'Em', 'Am'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Anime-style counter-line',
        description: 'A descending counter-line that fits the climb of the topline.',
        notes: [76, 74, 72, 71, 76, 74, 72, 71, 71, 67, 69, 71, 76, 74, 72, 69],
        chordSymbols: ['F', 'G', 'Em', 'Am'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-circle-fifths',
    group: 'Progressions',
    tag: 'Progressions · Circle of 5ths',
    title: 'Circle of 5ths walk',
    summary: 'Falling 5ths in sequence — the gear-train that drives jazz standards forward.',
    steps: [
      {
        type: 'theory',
        title: 'Down a 5th, every chord',
        text: `Each chord's root falls a perfect 5th into the next. Played around the whole circle: C → F → B♭ → E♭ → A♭ … back to C. Found in dozens of jazz standards as their backbone — short fragments give endless forward motion.`,
        diagram: { type: 'progression', chords: ['I7', 'IV7', '♭VII7', '♭III7', '♭VI7'] },
        audio: [[60, 64, 67, 70], [65, 69, 72, 75], [58, 62, 65, 68], [63, 67, 70, 73], [56, 60, 63, 66]],
        audioStyle: 'progression',
        references: [
          'Autumn Leaves',
          'Fly Me to the Moon',
          'I Will Survive (the chorus)',
        ],
      },
      {
        type: 'exercise',
        title: 'Hear five falling 5ths',
        description: 'Each root drops by a perfect 5th.',
        notes: [[60, 64, 67, 70], [65, 69, 72, 75], [58, 62, 65, 68], [63, 67, 70, 73], [56, 60, 63, 66]],
        chordSymbols: ['C7', 'F7', 'Bb7', 'Eb7', 'Ab7'],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Melody over the cycle',
        description: 'A line that lands on the chord 3rd at every change, across all five chords.',
        notes: [64, 67, 70, 64, 69, 72, 75, 69, 62, 65, 68, 62, 67, 70, 73, 67, 60, 63, 66, 60],
        chordSymbols: ['C7', 'F7', 'Bb7', 'Eb7', 'Ab7'],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking-bass cycle',
        description: 'A bass line walking through all five falling 5ths, four quarters per chord.',
        notes: [60, 64, 67, 70, 65, 69, 72, 70, 58, 62, 65, 63, 63, 67, 70, 68, 56, 60, 63, 66],
        chordSymbols: ['C7', 'F7', 'Bb7', 'Eb7', 'Ab7'],
        style: 'melody',
      },
    ],
  },
  {
    id: 'prog-blues-turnaround',
    group: 'Progressions',
    tag: 'Progressions · Blues',
    title: 'Blues turnaround',
    summary: 'The 4-bar phrase that sets up the next chorus of a blues. Pure DNA of the form.',
    steps: [
      {
        type: 'theory',
        title: 'The last four bars',
        text: `A blues turnaround is the I → V → I (or I → IV → I → V) phrase at the end of every 12-bar chorus. The walking bass line and the chromatic descent in the chord voicings are its signature.`,
        diagram: { type: 'progression', chords: ['I', 'IV', 'I', 'V'] },
        audio: [[48, 60, 64, 67], [53, 65, 69, 72], [48, 60, 64, 67], [55, 67, 71, 74]],
        audioStyle: 'progression',
        references: [
          'Sweet Home Chicago — last four bars of every chorus',
          'I Got My Mojo Working',
          "Every blues you've ever heard",
        ],
      },
      {
        type: 'exercise',
        title: 'Hear the turnaround',
        notes: [[48, 60, 64, 67], [53, 65, 69, 72], [48, 60, 64, 67], [55, 67, 71, 74]],
        chordSymbols: ['C', 'F', 'C', 'G'],
        style: 'progression',
        description: 'C – F – C – G.',
      },
      {
        type: 'exercise',
        title: 'Walking turnaround bassline',
        description: 'The classic walking-bass turnaround.',
        notes: [48, 50, 52, 53, 55, 53, 52, 50, 48, 50, 52, 55, 53, 55, 56, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lick that resolves home',
        description: "A blues guitar lick over the turnaround.",
        notes: [76, 79, 81, 79, 76, 75, 74, 72, 69, 67, 69, 72],
        chordSymbols: ['C', ['F', 'C'], 'G'],
        style: 'melody',
      },
    ],
  },
  // ================= BASS =================
  {
    id: 'walking-bass',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking Bass — Foundations',
    summary: 'Quarter notes per beat, landing on chord roots. The starting point.',
    steps: [
      {
        type: 'theory',
        title: 'The walking principle',
        text: `In a walking bass line each beat gets a quarter note. Beat 1 lands on the <strong>chord root</strong>, beat 3 typically on the <strong>5th</strong> or <strong>3rd</strong>, and beats 2 and 4 are <strong>connectors</strong> — scale or chromatic notes that lead the ear smoothly into the next chord.`,
        audio: [48, 52, 55, 60, 67, 64, 60, 55],
        references: [
          'Ray Brown (Oscar Peterson Trio)',
          'Paul Chambers (Miles Davis)',
          "Almost any swing-era jazz recording",
        ],
      },
      {
        type: 'exercise',
        title: 'Roots only',
        description: 'Just chord roots — the simplest walking line.',
        notes: [48, 48, 48, 48, 53, 53, 53, 53, 55, 55, 55, 55, 48, 48, 48, 48],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Roots + 5ths',
        description: 'Add the 5th on beat 3 — the second most stable note.',
        notes: [48, 55, 48, 55, 53, 60, 53, 60, 55, 62, 55, 62, 48, 55, 48, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Adding the 3rd',
        description: 'Each bar walks 1 – 3 – 5 – 3 over its chord. The 3rd on beats 2 and 4 adds chord colour.',
        notes: [48, 52, 55, 52, 53, 57, 60, 57, 55, 59, 62, 59, 48, 52, 55, 52],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Putting it together',
        description: 'Four bars over I, IV, V, I. Each bar starts on the root and uses chord tones — same idea, mixed direction so the line never feels mechanical.',
        notes: [48, 52, 55, 57, 53, 60, 57, 53, 55, 62, 59, 55, 48, 55, 52, 48],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-diatonic',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Diatonic Walks',
    summary: 'Use scale steps to connect roots — the staple of mainstream jazz bass lines.',
    steps: [
      {
        type: 'theory',
        title: 'Stepwise connection',
        text: `The most natural walking bass uses <strong>scale tones</strong> (notes in the key) to bridge chord roots. Each pair of bars is a small puzzle: you've got 4 beats, the next chord arrives on beat 5, and you need beats 1–4 to land on chord tones with smooth motion.`,
        audio: [48, 50, 52, 53, 53, 55, 57, 55, 55, 53, 52, 50, 48, 50, 52, 55],
        references: [
          'Autumn Leaves',
          'Blue Bossa',
        ],
      },
      {
        type: 'exercise',
        title: 'Walking up',
        description: 'Stepwise climb: 1 → 2 → 3 → 4 → land on IV chord root.',
        notes: [48, 50, 52, 53, 53, 55, 57, 59, 60, 59, 57, 55, 53, 52, 50, 48],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walking down',
        description: 'Descending diatonic walk over I → vi → IV → V.',
        notes: [60, 59, 57, 55, 57, 55, 53, 52, 53, 52, 50, 48, 55, 53, 52, 50],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walk + arpeggio mix',
        description: 'Mix scale steps with chord tones for variety.',
        notes: [48, 52, 55, 53, 53, 57, 60, 59, 55, 59, 62, 60, 48, 50, 52, 55],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-chromatic',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Chromatic Approach Notes',
    summary: 'A half-step into the next chord root makes any walk sound like jazz.',
    steps: [
      {
        type: 'theory',
        title: 'Land a half-step away',
        text: `The single biggest "jazz move" in walking bass: precede each chord root with a <strong>chromatic neighbour</strong> — a half-step above or below. It heightens the resolution at every bar line. With chromatic approach from below: ...root, 3rd, 5th, ♭root-of-next.`,
        audio: [48, 52, 55, 56, 53, 57, 60, 54, 55, 59, 62, 56, 48, 52, 55, 56],
        references: [
          'Ray Brown — every record he made',
          "Walter Page (Count Basie's bassist)",
        ],
      },
      {
        type: 'exercise',
        title: 'Approach from below',
        description: 'Last beat of each bar is one half-step below the next chord root — E→F, F♯→G, B→C, B→C.',
        notes: [48, 52, 55, 52, 53, 57, 60, 54, 55, 59, 62, 47, 48, 52, 55, 47],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Approach from above',
        description: 'Last beat is one half-step above the next root.',
        notes: [48, 52, 55, 54, 53, 57, 60, 56, 55, 59, 62, 49, 48, 52, 55, 49],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixed approach (above & below)',
        description: 'Alternate the direction for more variety.',
        notes: [48, 52, 55, 54, 53, 57, 60, 56, 55, 59, 62, 60, 48, 50, 52, 47],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-fifths',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking through the Cycle of 5ths',
    summary: 'Iconic patterns over jazz standards driven by falling 5ths.',
    steps: [
      {
        type: 'theory',
        title: 'Cycle in the bass',
        text: `Many jazz tunes have stretches where roots fall by 5ths (Cmaj7 → F7 → B♭maj7 → E♭7 …). Bassists love these because the line writes itself: root → 3rd → 5th → chromatic into next root. Pure forward motion.`,
        audio: [60, 64, 67, 70, 65, 69, 72, 75, 58, 62, 65, 68, 63, 67, 70, 73],
        references: [
          'All The Things You Are (the bridge)',
          'Autumn Leaves',
          'Sweet Georgia Brown',
        ],
      },
      {
        type: 'exercise',
        title: 'Five chords down a 5th each',
        description: 'Walking through five 7th chords, each root a 5th below the last.',
        notes: [60, 64, 67, 70, 65, 69, 72, 75, 58, 62, 65, 68, 63, 67, 70, 73, 56, 60, 63, 66],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Cycle with chromatic approach',
        description: 'Same cycle, with a half-step approach into each new root.',
        notes: [60, 64, 67, 66, 65, 69, 72, 71, 70, 62, 65, 64, 63, 67, 70, 69, 68, 60, 63, 66],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-inversions',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Inversions — 3rd & 5th in the Bass',
    summary: 'Land on chord tones other than the root for richer voice-leading.',
    steps: [
      {
        type: 'theory',
        title: 'You don\'t have to start on the root',
        text: `Every walking line doesn't need to land on the root every bar. Landing on the <strong>3rd</strong> (1st inversion in the bass) keeps the line moving smoothly between distant roots; landing on the <strong>5th</strong> (2nd inversion) creates suspension and pull.`,
        audio: [52, 55, 57, 60, 57, 60, 62, 65, 53, 55, 57, 60, 48, 52, 55, 57],
        references: [
          'Bill Evans Trio — bassist Scott LaFaro famously avoided roots',
          'Charles Mingus — chord-tone bass lines',
        ],
      },
      {
        type: 'exercise',
        title: '3rd in the bass',
        description: 'Each chord begins with its 3rd in the bass.',
        notes: [52, 55, 60, 55, 57, 60, 65, 60, 59, 62, 67, 62, 52, 55, 60, 55],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: '5th in the bass',
        description: 'Walking with each bar starting on the chord 5th.',
        notes: [55, 60, 64, 60, 60, 65, 69, 65, 62, 67, 71, 67, 55, 60, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Mixing positions',
        description: 'Alternate root, 3rd, 5th over four chords for a flowing line.',
        notes: [48, 52, 55, 52, 57, 60, 65, 60, 50, 53, 57, 53, 55, 59, 62, 59],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-doubletime',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Density & Rests',
    summary: 'Two contrasting tools: denser walking lines and strategic silences.',
    steps: [
      {
        type: 'theory',
        title: 'More motion or more space',
        text: `Once you have the four-quarters-per-bar walking pulse down, you can shape the line in two opposite directions. <strong>Denser</strong> — pack every quarter with chord and approach tones so the line constantly moves. <strong>Sparser</strong> — drop a beat to a rest, letting the harmony breathe. Both shape phrasing; you pick depending on the section.`,
        audio: [48, 50, 52, 53, 53, 55, 57, 55, 55, 53, 52, 50, 48, 50, 52, 55],
        references: [
          'Ron Carter (Miles Davis 60s quintet)',
          'Christian McBride',
        ],
      },
      {
        type: 'exercise',
        title: 'Dense walk',
        description: 'A line packed with chord and scale tones — every beat lands on a meaningful note.',
        notes: [48, 50, 52, 53, 50, 52, 53, 55, 53, 55, 57, 59, 55, 57, 59, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walk with rests on beat 2',
        description: 'Beat 2 of every bar is silent — the line breathes, and beats 1, 3, 4 carry more weight.',
        notes: [48, null, 55, 52, 53, null, 60, 57, 55, null, 62, 59, 48, null, 55, 47],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Walk with rests on beat 4',
        description: 'Silence on beat 4 leaves space before each chord change — a common phrasing trick.',
        notes: [48, 52, 55, null, 53, 57, 60, null, 55, 59, 62, null, 48, 52, 55, null],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-triplets',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Boogie, Triplets & Shuffle',
    summary: 'Chord-tone patterns, triplet fills and the shuffle 8th — three idioms that define swing and blues bass.',
    steps: [
      {
        type: 'theory',
        title: 'Patterns, triplets and the shuffle 8th',
        text: `Three idioms in one module. <strong>Boogie</strong> leans on a repeating chord-tone pattern (1-3-5-6-♭7-6-5-3) rather than a freshly-improvised walk. <strong>Triplet fills</strong> compress three notes into a single beat — usually on beat 4, propelling the line into the next bar. The <strong>shuffle 8th</strong> turns "1-and-2-and" into long-short, long-short by splitting each beat into a triplet-quarter + triplet-eighth (the long lands on the beat; the short is the "and" pushed late).`,
        audio: [48, 52, 55, 57, 58, 57, 55, 52, 53, 57, 60, 62, 63, 62, 60, 57],
        references: [
          'Boogie-woogie pianists',
          'Blues bassists like Willie Dixon',
          'Pete Johnson, Albert Ammons',
        ],
      },
      {
        type: 'exercise',
        title: 'Connecting note on beat 4',
        description: 'Beats 1-3 outline the chord; beat 4 is a passing note that leads chromatically into the next chord root.',
        notes: [48, 52, 55, 52, 53, 57, 60, 54, 55, 59, 62, 49, 48, 52, 55, 47],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Boogie bass pattern',
        description: 'The classic boogie shape per chord: root, 3rd, 5th, 6th, ♭7, 6th, 5th, 3rd.',
        notes: [48, 52, 55, 57, 58, 57, 55, 52, 53, 57, 60, 62, 63, 62, 60, 57],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Triplet fill on beat 4',
        description: 'Quarters on beats 1-3, then three triplet eighths on beat 4 sweep into the next bar.',
        notes: [
          48, 52, 55, { m: 53, t: 'et' }, { m: 54, t: 'et' }, { m: 55, t: 'et' },
          53, 57, 60, { m: 58, t: 'et' }, { m: 59, t: 'et' }, { m: 60, t: 'et' },
          55, 59, 62, { m: 49, t: 'et' }, { m: 48, t: 'et' }, { m: 47, t: 'et' },
          48, 52, 55, 52,
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Shuffle 8th feel',
        description: 'Each beat is a triplet-quarter + triplet-eighth pair — the "long-short" that drives every shuffle bassline. Eight notes per bar.',
        notes: [
          { m: 48, t: 'qt' }, { m: 52, t: 'et' }, { m: 55, t: 'qt' }, { m: 57, t: 'et' },
          { m: 58, t: 'qt' }, { m: 57, t: 'et' }, { m: 55, t: 'qt' }, { m: 52, t: 'et' },
          { m: 53, t: 'qt' }, { m: 57, t: 'et' }, { m: 60, t: 'qt' }, { m: 62, t: 'et' },
          { m: 63, t: 'qt' }, { m: 62, t: 'et' }, { m: 60, t: 'qt' }, { m: 57, t: 'et' },
        ],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-blues',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking the 12-bar Blues',
    summary: "A full chorus of walking bass over the blues. Classic Saturday-night sound.",
    steps: [
      {
        type: 'theory',
        title: 'Putting it all together',
        text: `A full 12-bar walking bassline mixes <strong>roots</strong>, <strong>chord tones</strong>, <strong>scale notes</strong> and <strong>chromatic approach</strong>. The form is: I I I I · IV IV I I · V IV I V. Bar 12 is a turnaround that pushes back to I.`,
        audio: [48, 52, 55, 57, 53, 57, 60, 53, 48, 52, 55, 57, 53, 57, 60, 53, 48, 52, 55, 57, 55, 50, 52, 48],
        references: [
          'Sweet Home Chicago',
          'Hoochie Coochie Man',
          "Stormy Monday Blues",
        ],
      },
      {
        type: 'exercise',
        title: 'Bars 1-4 (I chord)',
        description: 'Walking over the tonic for four bars.',
        notes: [48, 52, 55, 57, 48, 52, 55, 53, 48, 52, 55, 57, 48, 50, 52, 53],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bars 5-8 (IV → I)',
        description: 'Walk over IV for two bars then back to I.',
        notes: [53, 57, 60, 62, 53, 57, 60, 58, 48, 52, 55, 57, 48, 52, 55, 53],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Bars 9-12 (V IV I V — turnaround)',
        description: 'V → IV → I → V turnaround.',
        notes: [55, 59, 62, 64, 53, 57, 60, 58, 48, 52, 55, 57, 55, 50, 52, 48],
        style: 'melody',
      },
    ],
  },
  {
    id: 'walking-bass-iivi',
    group: 'Walking Bass',
    tag: 'Bass · Walking',
    title: 'Walking ii–V–I (Jazz)',
    summary: "The most-played bass progression in jazz. Master this and you'll fit in any session.",
    steps: [
      {
        type: 'theory',
        title: 'The core jazz cadence',
        text: `<strong>ii–V–I</strong> on its own is two bars (one bar of ii, one bar of V) followed by I. The bassist's job is to walk from the ii's root to the V's root to the I's root with smooth voice leading and (often) chromatic approach.`,
        audio: [50, 53, 57, 56, 55, 59, 62, 59, 60, 64, 67, 64],
        references: [
          'Autumn Leaves',
          'All The Things You Are',
          'A Night in Tunisia',
        ],
      },
      {
        type: 'exercise',
        title: 'Basic ii–V–I walk',
        description: 'Roots, scale tones, chromatic approach into each chord.',
        notes: [50, 53, 57, 56, 55, 59, 62, 59, 60, 64, 67, 64],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With double-time fills',
        description: 'The same ii–V–I walk in eighth notes — eight notes per bar instead of four. Pure forward motion.',
        notes: [
          { m: 50, t: 'e' }, { m: 53, t: 'e' }, { m: 55, t: 'e' }, { m: 57, t: 'e' }, { m: 56, t: 'e' }, { m: 55, t: 'e' }, { m: 53, t: 'e' }, { m: 50, t: 'e' },
          { m: 55, t: 'e' }, { m: 59, t: 'e' }, { m: 62, t: 'e' }, { m: 64, t: 'e' }, { m: 65, t: 'e' }, { m: 64, t: 'e' }, { m: 62, t: 'e' }, { m: 59, t: 'e' },
          { m: 60, t: 'e' }, { m: 64, t: 'e' }, { m: 67, t: 'e' }, { m: 71, t: 'e' }, { m: 72, t: 'e' }, { m: 71, t: 'e' }, { m: 67, t: 'e' }, { m: 64, t: 'e' },
        ],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'With substitutions',
        description: 'Chromatic substitution: ii → ♭II → I (tritone substitute).',
        notes: [50, 53, 57, 60, 61, 64, 67, 70, 60, 64, 67, 64],
        style: 'melody',
      },
    ],
  },
  // The walking-bass generator that used to live here moved to the Practice
  // view (src/js/ui/practice-studies.js → "walking-bass-workout"). Learn keeps
  // the conceptual modules; Practice keeps the open-ended generators.
  // ================= READING =================
  {
    id: 'reading-rhythms',
    group: 'Reading',
    tag: 'Reading',
    title: 'Quarters, eighths and rests',
    summary: 'Three rhythm primitives — one beat, half a beat, and silence.',
    steps: [
      {
        type: 'theory',
        title: 'Beat by beat',
        text: `A <strong>quarter note</strong> takes one beat — in 4/4 time, four of them fill a bar. An <strong>eighth note</strong> takes half a beat, so two of them fit in one beat. A <strong>quarter rest</strong> is one silent beat. Combining these three primitives is the simplest way rhythm gets its character: where you place a silence or a faster note is just as expressive as where you place a sound.`,
      },
      {
        type: 'exercise',
        title: 'Steady quarters',
        description: 'A note on every beat. Feel the steady pulse.',
        notes: [60, 60, 60, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'A rest on beat 3',
        description: 'The third beat is silent. Notice how the rest changes the phrasing.',
        notes: [60, 62, null, 60, 64, 62, null, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Adding eighth notes',
        description: 'Each second beat is split into two eighth notes — twice as fast. Listen to the ride feeling.',
        notes: [
          60, { m: 62, t: 'e' }, { m: 64, t: 'e' }, 65,
          67, { m: 65, t: 'e' }, { m: 64, t: 'e' }, 60,
        ],
        style: 'melody',
      },
    ],
  },
  // ================= DUETS =================
  {
    id: 'duets',
    group: 'Duets',
    tag: 'Duets · Counterpoint',
    title: 'Two-voice basics',
    summary: 'Hear how two melodies move together. The simplest counterpoint patterns.',
    steps: [
      {
        type: 'theory',
        title: 'Two voices, two paths',
        text: `When two melodies play simultaneously, the interesting question is how they relate. <strong>Parallel motion</strong> moves both voices the same way; <strong>contrary motion</strong> sends them in opposite directions; <strong>oblique motion</strong> keeps one voice still while the other moves. Mixing all three is the heart of counterpoint.`,
      },
      {
        type: 'exercise',
        title: 'Parallel thirds',
        description: 'Both voices ascend the C major scale, always a third apart.',
        notes: [
          [60, 64], [62, 65], [64, 67], [65, 69], [67, 71], [69, 72], [71, 74], [72, 76],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Contrary motion',
        description: 'One voice goes up while the other goes down — they meet and cross.',
        notes: [
          [60, 84], [62, 81], [64, 79], [65, 77], [67, 76], [69, 74], [71, 72], [72, 71],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Call &amp; response',
        description: 'Two voices trade short melodic phrases — one calls, the other answers.',
        notes: [
          [60, 60], [62, 60], [64, 60], [65, 60],
          [60, 65], [60, 64], [60, 62], [60, 60],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Upper voice on its own',
        description: 'Just the top line of the parallel-thirds duet — useful to internalise before adding the second voice.',
        notes: [64, 65, 67, 69, 71, 72, 74, 76],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lower voice on its own',
        description: 'Same exercise from the bottom voice\'s perspective.',
        notes: [60, 62, 64, 65, 67, 69, 71, 72],
        style: 'melody',
      },
    ],
  },
  // ================= COUNTERPOINT =================
  // Five-module track loosely following Fux's species-counterpoint
  // ladder. Each exercise plays both voices as a chord-style two-note
  // event so the listener hears the vertical interval; the standalone
  // "voice 1 / voice 2" exercises at the end of each module let
  // learners drill each line independently before combining.
  {
    id: 'counterpoint-species-1',
    group: 'Counterpoint',
    tag: 'Counterpoint · Species 1',
    title: 'Counterpoint I — Note against note',
    summary: 'First-species counterpoint: one note per beat in each voice, only consonant intervals, contrary motion preferred.',
    steps: [
      {
        type: 'theory',
        title: 'The rules in one paragraph',
        text: `First-species counterpoint pairs a <em>cantus firmus</em> (a slow given melody) with a second voice moving at the same pace — one note against one note. The only allowed vertical intervals are <strong>perfect consonances</strong> (unison, 5th, octave) and <strong>imperfect consonances</strong> (3rd, 6th). Avoid parallel 5ths and octaves, and favour <strong>contrary motion</strong> (one voice up while the other goes down). The first and last bars should land on the tonic with a perfect consonance.`,
        references: [
          "Fux's Gradus ad Parnassum — 1725, the canonical textbook",
          'Schoenberg, Preliminary Exercises in Counterpoint',
        ],
      },
      {
        type: 'exercise',
        title: 'Cantus firmus in C major',
        description: 'A simple 8-bar cantus firmus on the lower voice. Sing it alone first — every entry is a whole step or third away from its neighbour.',
        notes: [60, 62, 64, 65, 67, 65, 64, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Counterpoint above the cantus',
        description: 'A first-species line over the same cantus firmus. Every vertical interval is a 3rd, 5th, 6th or octave; contrary motion appears at bars 2-3 and 6-7.',
        notes: [
          [60, 67], [62, 71], [64, 72], [65, 69],
          [67, 71], [65, 72], [64, 71], [60, 72],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Counterpoint below the cantus',
        description: 'Same cantus on top; the lower voice supplies first-species counterpoint. Notice how the bottom voice mirrors the top\'s direction at the cadence.',
        notes: [
          [60, 48], [62, 53], [64, 52], [65, 50],
          [67, 48], [65, 53], [64, 52], [60, 48],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Upper voice on its own',
        description: 'Just the upper counterpoint line from the second exercise — useful to internalise before mixing voices.',
        notes: [67, 71, 72, 69, 71, 72, 71, 72],
        style: 'melody',
      },
    ],
  },
  {
    id: 'counterpoint-passing-tones',
    group: 'Counterpoint',
    tag: 'Counterpoint · Species 2',
    title: 'Counterpoint II — Passing tones',
    summary: 'Second species adds a non-chord tone between consonances. Two notes per beat in the counter voice.',
    steps: [
      {
        type: 'theory',
        title: 'Dissonance, but only in passing',
        text: `Second-species counterpoint speeds up the counter voice: <strong>two half-notes for every whole note</strong> in the cantus firmus. The first half-note must be a consonance with the cantus; the second can be a <strong>passing tone</strong> (a dissonant note approached and left by step) on the weak beat. This is where dissonance enters Western counterpoint — controlled, fleeting, always between two consonances.`,
        references: [
          'Fux, Gradus ad Parnassum, Species 2',
        ],
      },
      {
        type: 'exercise',
        title: 'Counter voice with passing tones (ascending)',
        description: 'Each cantus bar gets two notes from the counter voice — the second beat is often a passing tone smoothing the leap.',
        notes: [
          [60, 67], [60, 69],
          [62, 71], [62, 72],
          [64, 72], [64, 74],
          [65, 72], [65, 71],
          [67, 71], [67, 69],
          [65, 67], [65, 65],
          [64, 64], [64, 62],
          [60, 60], [60, 60],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Counter voice with passing tones (descending)',
        description: 'Now the upper voice starts high and walks down through passing tones to land back on the tonic in unison.',
        notes: [
          [60, 76], [60, 74],
          [62, 72], [62, 71],
          [64, 72], [64, 71],
          [65, 69], [65, 67],
          [67, 71], [67, 69],
          [64, 67], [64, 65],
          [62, 64], [62, 62],
          [60, 60], [60, 60],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Counter voice on its own',
        description: 'The upper line from the ascending example — sing it through to feel the passing-tone smoothing.',
        notes: [67, 69, 71, 72, 72, 74, 72, 71, 71, 69, 67, 65, 64, 62, 60, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Cantus firmus on its own',
        description: 'The lower (slower) voice of the previous examples — held whole-note tones outlining the harmony underneath the passing tones.',
        notes: [{ m: 60, t: 'h' }, { m: 62, t: 'h' }, { m: 64, t: 'h' }, { m: 65, t: 'h' }, { m: 67, t: 'h' }, { m: 65, t: 'h' }, { m: 64, t: 'h' }, { m: 60, t: 'h' }],
        style: 'melody',
      },
    ],
  },
  {
    id: 'counterpoint-suspensions',
    group: 'Counterpoint',
    tag: 'Counterpoint · Species 4',
    title: 'Counterpoint IV — Suspensions',
    summary: 'A note from the previous bar is held over a new harmony — creating tension — then resolved down by step.',
    steps: [
      {
        type: 'theory',
        title: '4-3, 7-6, 9-8 — preparation, suspension, resolution',
        text: `A suspension has three steps: <strong>preparation</strong> (a consonance), <strong>suspension</strong> (the same note held into the next bar, now dissonant), and <strong>resolution</strong> (the suspended note moves down by step to a consonance). Common patterns are named by their intervals: a <strong>4-3 suspension</strong> resolves a 4th down to a 3rd, a <strong>7-6</strong> resolves a 7th to a 6th, a <strong>9-8</strong> resolves a 9th to an octave. Suspensions are how Renaissance and Baroque composers built emotional weight without changing the rhythm.`,
        references: [
          "J.S. Bach — countless examples in his chorales and inventions",
          'Palestrina — the gold standard of suspended-line writing',
        ],
      },
      {
        type: 'exercise',
        title: '4-3 suspension chain',
        description: 'Each bar prepares, holds and resolves a 4-3 suspension over the lower voice. The dissonance is brief but unmistakable.',
        notes: [
          [60, 65], [60, 64],
          [62, 67], [62, 65],
          [64, 69], [64, 67],
          [65, 72], [65, 69],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: '7-6 suspension chain',
        description: 'A series of 7-6 suspensions — the most singable suspension type, sometimes called the "sigh" pattern.',
        notes: [
          [60, 71], [60, 69],
          [62, 72], [62, 71],
          [64, 74], [64, 72],
          [65, 76], [65, 74],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Upper voice on its own',
        description: 'The suspended upper voice from the 7-6 chain — every pair "leans" down a step.',
        notes: [71, 69, 72, 71, 74, 72, 76, 74],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lower voice on its own',
        description: 'The bass line from the same chain — slow, anchoring whole notes that make the suspensions audible above.',
        notes: [{ m: 60, t: 'h' }, { m: 62, t: 'h' }, { m: 64, t: 'h' }, { m: 65, t: 'h' }],
        style: 'melody',
      },
    ],
  },
  {
    id: 'counterpoint-imitation',
    group: 'Counterpoint',
    tag: 'Counterpoint · Imitation',
    title: 'Imitation & Canon',
    summary: 'Voice 2 enters after voice 1 with the same melodic shape — the building block of fugues, rounds and inventions.',
    steps: [
      {
        type: 'theory',
        title: 'Same notes, different time',
        text: `<strong>Imitation</strong> is the simplest contrapuntal trick: voice 2 enters a few beats after voice 1 with the same melodic shape. When the imitation continues exactly — every interval, every rhythm — it becomes a <strong>canon</strong>. The interval and beat-offset of the entry give canons their flavour: <strong>at the octave</strong> (most common), <strong>at the fifth</strong> (Pachelbel's), <strong>at the unison</strong> (rounds like Frère Jacques).`,
        references: [
          'Pachelbel, Canon in D — canon at the unison, three voices',
          'Bach, the Goldberg Variations — every third variation is a canon',
        ],
      },
      {
        type: 'exercise',
        title: 'Canon at the octave',
        description: 'Both voices play the same melodic shape, but voice 2 (lower) lags voice 1 by two beats — so what you hear in any column is voice 1 at "step n" against voice 2 at "step n−2".',
        notes: [
          [60, 48], [62, 48],
          [64, 48], [65, 50],
          [67, 52], [69, 53],
          [67, 55], [65, 57],
          [64, 55], [62, 53],
          [60, 52], [60, 50],
          [60, 48], [60, 48],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Lead voice on its own',
        description: 'Just the lead phrase — sing or play it alone so the shape is familiar before stacking it.',
        notes: [60, 62, 64, 65, 67, 69, 67, 65, 64, 62, 60, 60],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Following voice on its own',
        description: 'The follower line — same shape as the lead, an octave below.',
        notes: [48, 50, 52, 53, 55, 57, 55, 53, 52, 50, 48, 48],
        style: 'melody',
      },
    ],
  },
  {
    id: 'counterpoint-free',
    group: 'Counterpoint',
    tag: 'Counterpoint · Free',
    title: 'Free counterpoint',
    summary: 'Mixing species — passing tones, suspensions and imitation in one short piece.',
    steps: [
      {
        type: 'theory',
        title: 'Combining the tools',
        text: `Free (or fifth-species) counterpoint drops the per-species restrictions and combines everything: <strong>passing tones</strong> for forward motion, <strong>suspensions</strong> for emotional weight, brief <strong>imitative entries</strong> for unity, all over a slowly moving cantus firmus or chord progression. Bach's two-part inventions are the canonical examples — short, didactic, dense.`,
        references: [
          "Bach, Invention No. 1 in C Major (BWV 772) — eight bars of free counterpoint to learn from",
        ],
      },
      {
        type: 'exercise',
        title: 'Invention-style opening',
        description: 'Eight bars combining first-species roots, a passing tone in bar 3, and a 7-6 suspension in bar 6.',
        notes: [
          [60, 67], [60, 69],
          [62, 71], [62, 72],
          [64, 72], [64, 71],
          [65, 69], [65, 67],
          [67, 71], [67, 72],
          [65, 74], [65, 72],
          [64, 72], [64, 71],
          [60, 72], [60, 72],
        ],
        style: 'progression',
      },
      {
        type: 'exercise',
        title: 'Upper voice on its own',
        description: 'The upper line from the invention-style example — phrased as a melody you might recognise from Bach.',
        notes: [67, 69, 71, 72, 72, 71, 69, 67, 71, 72, 74, 72, 72, 71, 72, 72],
        style: 'melody',
      },
      {
        type: 'exercise',
        title: 'Lower voice on its own',
        description: 'The lower (cantus-like) voice from the same example — slower, anchoring the harmony.',
        notes: [60, 62, 64, 65, 67, 65, 64, 60],
        style: 'melody',
      },
    ],
  },
];

export const GROUPS = ['Scales', 'Chords', 'Progressions', 'Walking Bass', 'Reading', 'Duets', 'Counterpoint'];
